package ntx:scenario-scheduler@0.1.0;

use ntx:scenario-actions-executor/action-component@0.1.0;
use ntx:scenario-eventbus/event-bus@0.1.0;
use ntx:host/rx-ring@0.1.0;
use ntx:host/resources@0.1.0;
use ntx:host/udp-socket-control@0.1.0;
use ntx:core-types/types@0.1.0;

/// Scheduler 主循环入口
interface scheduler-component {
    /// config-dir 指向 workflow/workbook/load 的所在目录
    run: func(config-dir: string) -> result<_, string>;
}

world scheduler-main {
    import action-component;
    import event-bus;
    import rx-ring;
    import resources;
    import udp-socket-control;
    import types;
    export scheduler-component;
}

