// https://github.com/WebAssembly/wasi-sockets/blob/main/TcpSocketOperationalSemantics.md
package component:http-send;
use wasi:sockets/tcp-create-socket@0.2.8;
use wasi:sockets/tcp@0.2.8;
use wasi:sockets/network@0.2.8;
use wasi:sockets/instance-network@0.2.8;
/// An example world for the component to target.
world example {
    import tcp-create-socket;
    import tcp;
    import network;
    import instance-network;
    export start: func() -> string;
}
