// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod scheduler {
        pub mod core_libs {
            /// Core scheduler data structures and DSL parsing
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Resource definition
                #[derive(Clone)]
                pub struct ResourceDef {
                    pub id: _rt::String,
                    pub resource_type: _rt::String,
                    pub properties: _rt::String,
                }
                impl ::core::fmt::Debug for ResourceDef {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ResourceDef")
                            .field("id", &self.id)
                            .field("resource-type", &self.resource_type)
                            .field("properties", &self.properties)
                            .finish()
                    }
                }
                /// Export definition
                #[derive(Clone)]
                pub struct ExportDef {
                    pub export_type: _rt::String,
                    pub name: _rt::String,
                    pub scope: Option<_rt::String>,
                    pub default_value: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ExportDef {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExportDef")
                            .field("export-type", &self.export_type)
                            .field("name", &self.name)
                            .field("scope", &self.scope)
                            .field("default-value", &self.default_value)
                            .finish()
                    }
                }
                /// Action definition
                #[derive(Clone)]
                pub struct ActionDef {
                    pub id: _rt::String,
                    pub call: _rt::String,
                    pub with_params: _rt::String,
                    /// JSON string of parameters
                    pub exports: _rt::Vec<ExportDef>,
                }
                impl ::core::fmt::Debug for ActionDef {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ActionDef")
                            .field("id", &self.id)
                            .field("call", &self.call)
                            .field("with-params", &self.with_params)
                            .field("exports", &self.exports)
                            .finish()
                    }
                }
                /// Node type
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum NodeType {
                    Action,
                    End,
                }
                impl ::core::fmt::Debug for NodeType {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            NodeType::Action => {
                                f.debug_tuple("NodeType::Action").finish()
                            }
                            NodeType::End => f.debug_tuple("NodeType::End").finish(),
                        }
                    }
                }
                impl NodeType {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> NodeType {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => NodeType::Action,
                            1 => NodeType::End,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Workflow edge
                #[derive(Clone)]
                pub struct WorkflowEdge {
                    pub to: _rt::String,
                    pub condition: Option<_rt::String>,
                    pub label: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for WorkflowEdge {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("WorkflowEdge")
                            .field("to", &self.to)
                            .field("condition", &self.condition)
                            .field("label", &self.label)
                            .finish()
                    }
                }
                /// Workflow node
                #[derive(Clone)]
                pub struct WorkflowNode {
                    pub id: _rt::String,
                    pub node_type: NodeType,
                    pub action: Option<_rt::String>,
                    pub edges: _rt::Vec<WorkflowEdge>,
                }
                impl ::core::fmt::Debug for WorkflowNode {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("WorkflowNode")
                            .field("id", &self.id)
                            .field("node-type", &self.node_type)
                            .field("action", &self.action)
                            .field("edges", &self.edges)
                            .finish()
                    }
                }
                /// A workflow scenario parsed from YAML
                #[derive(Clone)]
                pub struct Scenario {
                    pub version: _rt::String,
                    pub name: _rt::String,
                    pub resources: _rt::Vec<ResourceDef>,
                    pub actions: _rt::Vec<ActionDef>,
                    pub nodes: _rt::Vec<WorkflowNode>,
                }
                impl ::core::fmt::Debug for Scenario {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Scenario")
                            .field("version", &self.version)
                            .field("name", &self.name)
                            .field("resources", &self.resources)
                            .field("actions", &self.actions)
                            .field("nodes", &self.nodes)
                            .finish()
                    }
                }
                #[doc(hidden)]
                macro_rules! __export_scheduler_core_libs_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_core_libs_types_0_1_0_cabi;
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod parser {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Scenario = super::super::super::super::exports::scheduler::core_libs::types::Scenario;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_parse_scenario_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::parse_scenario(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::exports::scheduler::core_libs::types::Scenario {
                                version: version3,
                                name: name3,
                                resources: resources3,
                                actions: actions3,
                                nodes: nodes3,
                            } = e;
                            let vec4 = (version3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (name3.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr2
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                            let vec10 = resources3;
                            let len10 = vec10.len();
                            let layout10 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec10.len() * (6 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result10 = if layout10.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout10).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout10);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec10.into_iter().enumerate() {
                                let base = result10
                                    .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::exports::scheduler::core_libs::types::ResourceDef {
                                        id: id6,
                                        resource_type: resource_type6,
                                        properties: properties6,
                                    } = e;
                                    let vec7 = (id6.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *base.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                                    let vec8 = (resource_type6.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                    let vec9 = (properties6.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                }
                            }
                            *ptr2
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr2
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result10;
                            let vec21 = actions3;
                            let len21 = vec21.len();
                            let layout21 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec21.len() * (8 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result21 = if layout21.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout21).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout21);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec21.into_iter().enumerate() {
                                let base = result21
                                    .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::exports::scheduler::core_libs::types::ActionDef {
                                        id: id11,
                                        call: call11,
                                        with_params: with_params11,
                                        exports: exports11,
                                    } = e;
                                    let vec12 = (id11.into_bytes()).into_boxed_slice();
                                    let ptr12 = vec12.as_ptr().cast::<u8>();
                                    let len12 = vec12.len();
                                    ::core::mem::forget(vec12);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len12;
                                    *base.add(0).cast::<*mut u8>() = ptr12.cast_mut();
                                    let vec13 = (call11.into_bytes()).into_boxed_slice();
                                    let ptr13 = vec13.as_ptr().cast::<u8>();
                                    let len13 = vec13.len();
                                    ::core::mem::forget(vec13);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len13;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr13.cast_mut();
                                    let vec14 = (with_params11.into_bytes()).into_boxed_slice();
                                    let ptr14 = vec14.as_ptr().cast::<u8>();
                                    let len14 = vec14.len();
                                    ::core::mem::forget(vec14);
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len14;
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr14.cast_mut();
                                    let vec20 = exports11;
                                    let len20 = vec20.len();
                                    let layout20 = _rt::alloc::Layout::from_size_align_unchecked(
                                        vec20.len() * (10 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                    let result20 = if layout20.size() != 0 {
                                        let ptr = _rt::alloc::alloc(layout20).cast::<u8>();
                                        if ptr.is_null() {
                                            _rt::alloc::handle_alloc_error(layout20);
                                        }
                                        ptr
                                    } else {
                                        ::core::ptr::null_mut()
                                    };
                                    for (i, e) in vec20.into_iter().enumerate() {
                                        let base = result20
                                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            let super::super::super::super::exports::scheduler::core_libs::types::ExportDef {
                                                export_type: export_type15,
                                                name: name15,
                                                scope: scope15,
                                                default_value: default_value15,
                                            } = e;
                                            let vec16 = (export_type15.into_bytes()).into_boxed_slice();
                                            let ptr16 = vec16.as_ptr().cast::<u8>();
                                            let len16 = vec16.len();
                                            ::core::mem::forget(vec16);
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len16;
                                            *base.add(0).cast::<*mut u8>() = ptr16.cast_mut();
                                            let vec17 = (name15.into_bytes()).into_boxed_slice();
                                            let ptr17 = vec17.as_ptr().cast::<u8>();
                                            let len17 = vec17.len();
                                            ::core::mem::forget(vec17);
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len17;
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr17.cast_mut();
                                            match scope15 {
                                                Some(e) => {
                                                    *base
                                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (1i32) as u8;
                                                    let vec18 = (e.into_bytes()).into_boxed_slice();
                                                    let ptr18 = vec18.as_ptr().cast::<u8>();
                                                    let len18 = vec18.len();
                                                    ::core::mem::forget(vec18);
                                                    *base
                                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len18;
                                                    *base
                                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = ptr18.cast_mut();
                                                }
                                                None => {
                                                    *base
                                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (0i32) as u8;
                                                }
                                            };
                                            match default_value15 {
                                                Some(e) => {
                                                    *base
                                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (1i32) as u8;
                                                    let vec19 = (e.into_bytes()).into_boxed_slice();
                                                    let ptr19 = vec19.as_ptr().cast::<u8>();
                                                    let len19 = vec19.len();
                                                    ::core::mem::forget(vec19);
                                                    *base
                                                        .add(9 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len19;
                                                    *base
                                                        .add(8 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = ptr19.cast_mut();
                                                }
                                                None => {
                                                    *base
                                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (0i32) as u8;
                                                }
                                            };
                                        }
                                    }
                                    *base
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len20;
                                    *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = result20;
                                }
                            }
                            *ptr2
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len21;
                            *ptr2
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result21;
                            let vec30 = nodes3;
                            let len30 = vec30.len();
                            let layout30 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec30.len() * (8 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result30 = if layout30.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout30).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout30);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec30.into_iter().enumerate() {
                                let base = result30
                                    .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::exports::scheduler::core_libs::types::WorkflowNode {
                                        id: id22,
                                        node_type: node_type22,
                                        action: action22,
                                        edges: edges22,
                                    } = e;
                                    let vec23 = (id22.into_bytes()).into_boxed_slice();
                                    let ptr23 = vec23.as_ptr().cast::<u8>();
                                    let len23 = vec23.len();
                                    ::core::mem::forget(vec23);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len23;
                                    *base.add(0).cast::<*mut u8>() = ptr23.cast_mut();
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (node_type22.clone() as i32) as u8;
                                    match action22 {
                                        Some(e) => {
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (1i32) as u8;
                                            let vec24 = (e.into_bytes()).into_boxed_slice();
                                            let ptr24 = vec24.as_ptr().cast::<u8>();
                                            let len24 = vec24.len();
                                            ::core::mem::forget(vec24);
                                            *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len24;
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr24.cast_mut();
                                        }
                                        None => {
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (0i32) as u8;
                                        }
                                    };
                                    let vec29 = edges22;
                                    let len29 = vec29.len();
                                    let layout29 = _rt::alloc::Layout::from_size_align_unchecked(
                                        vec29.len() * (8 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                    let result29 = if layout29.size() != 0 {
                                        let ptr = _rt::alloc::alloc(layout29).cast::<u8>();
                                        if ptr.is_null() {
                                            _rt::alloc::handle_alloc_error(layout29);
                                        }
                                        ptr
                                    } else {
                                        ::core::ptr::null_mut()
                                    };
                                    for (i, e) in vec29.into_iter().enumerate() {
                                        let base = result29
                                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            let super::super::super::super::exports::scheduler::core_libs::types::WorkflowEdge {
                                                to: to25,
                                                condition: condition25,
                                                label: label25,
                                            } = e;
                                            let vec26 = (to25.into_bytes()).into_boxed_slice();
                                            let ptr26 = vec26.as_ptr().cast::<u8>();
                                            let len26 = vec26.len();
                                            ::core::mem::forget(vec26);
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len26;
                                            *base.add(0).cast::<*mut u8>() = ptr26.cast_mut();
                                            match condition25 {
                                                Some(e) => {
                                                    *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (1i32) as u8;
                                                    let vec27 = (e.into_bytes()).into_boxed_slice();
                                                    let ptr27 = vec27.as_ptr().cast::<u8>();
                                                    let len27 = vec27.len();
                                                    ::core::mem::forget(vec27);
                                                    *base
                                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len27;
                                                    *base
                                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = ptr27.cast_mut();
                                                }
                                                None => {
                                                    *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (0i32) as u8;
                                                }
                                            };
                                            match label25 {
                                                Some(e) => {
                                                    *base
                                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (1i32) as u8;
                                                    let vec28 = (e.into_bytes()).into_boxed_slice();
                                                    let ptr28 = vec28.as_ptr().cast::<u8>();
                                                    let len28 = vec28.len();
                                                    ::core::mem::forget(vec28);
                                                    *base
                                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len28;
                                                    *base
                                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = ptr28.cast_mut();
                                                }
                                                None => {
                                                    *base
                                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<u8>() = (0i32) as u8;
                                                }
                                            };
                                        }
                                    }
                                    *base
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len29;
                                    *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = result29;
                                }
                            }
                            *ptr2
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len30;
                            *ptr2
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result30;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec31 = (e.into_bytes()).into_boxed_slice();
                            let ptr31 = vec31.as_ptr().cast::<u8>();
                            let len31 = vec31.len();
                            ::core::mem::forget(vec31);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len31;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr31.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_parse_scenario<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base13 = l5;
                            let len13 = l6;
                            for i in 0..len13 {
                                let base = base13
                                    .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l7 = *base.add(0).cast::<*mut u8>();
                                    let l8 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                    let l9 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l10 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                    let l11 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l12 = *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l11, l12, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base13,
                                len13 * (6 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l14 = *arg0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l15 = *arg0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base35 = l14;
                            let len35 = l15;
                            for i in 0..len35 {
                                let base = base35
                                    .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l16 = *base.add(0).cast::<*mut u8>();
                                    let l17 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l16, l17, 1);
                                    let l18 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l19 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l18, l19, 1);
                                    let l20 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l21 = *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l20, l21, 1);
                                    let l22 = *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l23 = *base
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base34 = l22;
                                    let len34 = l23;
                                    for i in 0..len34 {
                                        let base = base34
                                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            let l24 = *base.add(0).cast::<*mut u8>();
                                            let l25 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l24, l25, 1);
                                            let l26 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l27 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l26, l27, 1);
                                            let l28 = i32::from(
                                                *base
                                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<u8>(),
                                            );
                                            match l28 {
                                                0 => {}
                                                _ => {
                                                    let l29 = *base
                                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l30 = *base
                                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l29, l30, 1);
                                                }
                                            }
                                            let l31 = i32::from(
                                                *base
                                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<u8>(),
                                            );
                                            match l31 {
                                                0 => {}
                                                _ => {
                                                    let l32 = *base
                                                        .add(8 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l33 = *base
                                                        .add(9 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l32, l33, 1);
                                                }
                                            }
                                        }
                                    }
                                    _rt::cabi_dealloc(
                                        base34,
                                        len34 * (10 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                }
                            }
                            _rt::cabi_dealloc(
                                base35,
                                len35 * (8 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l36 = *arg0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l37 = *arg0
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base54 = l36;
                            let len54 = l37;
                            for i in 0..len54 {
                                let base = base54
                                    .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l38 = *base.add(0).cast::<*mut u8>();
                                    let l39 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l38, l39, 1);
                                    let l40 = i32::from(
                                        *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    match l40 {
                                        0 => {}
                                        _ => {
                                            let l41 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l42 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l41, l42, 1);
                                        }
                                    }
                                    let l43 = *base
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l44 = *base
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base53 = l43;
                                    let len53 = l44;
                                    for i in 0..len53 {
                                        let base = base53
                                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            let l45 = *base.add(0).cast::<*mut u8>();
                                            let l46 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l45, l46, 1);
                                            let l47 = i32::from(
                                                *base
                                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<u8>(),
                                            );
                                            match l47 {
                                                0 => {}
                                                _ => {
                                                    let l48 = *base
                                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l49 = *base
                                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l48, l49, 1);
                                                }
                                            }
                                            let l50 = i32::from(
                                                *base
                                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<u8>(),
                                            );
                                            match l50 {
                                                0 => {}
                                                _ => {
                                                    let l51 = *base
                                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l52 = *base
                                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l51, l52, 1);
                                                }
                                            }
                                        }
                                    }
                                    _rt::cabi_dealloc(
                                        base53,
                                        len53 * (8 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                }
                            }
                            _rt::cabi_dealloc(
                                base54,
                                len54 * (8 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l55 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l56 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l55, l56, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_scenario_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: *mut u8,
                    arg9: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let base11 = arg4;
                    let len11 = arg5;
                    let mut result11 = _rt::Vec::with_capacity(len11);
                    for i in 0..len11 {
                        let base = base11
                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                        let e11 = {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len4 = l3;
                            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                            let l5 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len7 = l6;
                            let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                            let l8 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len10 = l9;
                            let bytes10 = _rt::Vec::from_raw_parts(
                                l8.cast(),
                                len10,
                                len10,
                            );
                            super::super::super::super::exports::scheduler::core_libs::types::ResourceDef {
                                id: _rt::string_lift(bytes4),
                                resource_type: _rt::string_lift(bytes7),
                                properties: _rt::string_lift(bytes10),
                            }
                        };
                        result11.push(e11);
                    }
                    _rt::cabi_dealloc(
                        base11,
                        len11 * (6 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let base38 = arg6;
                    let len38 = arg7;
                    let mut result38 = _rt::Vec::with_capacity(len38);
                    for i in 0..len38 {
                        let base = base38
                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                        let e38 = {
                            let l12 = *base.add(0).cast::<*mut u8>();
                            let l13 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len14 = l13;
                            let bytes14 = _rt::Vec::from_raw_parts(
                                l12.cast(),
                                len14,
                                len14,
                            );
                            let l15 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l16 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len17 = l16;
                            let bytes17 = _rt::Vec::from_raw_parts(
                                l15.cast(),
                                len17,
                                len17,
                            );
                            let l18 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l19 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len20 = l19;
                            let bytes20 = _rt::Vec::from_raw_parts(
                                l18.cast(),
                                len20,
                                len20,
                            );
                            let l21 = *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l22 = *base
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base37 = l21;
                            let len37 = l22;
                            let mut result37 = _rt::Vec::with_capacity(len37);
                            for i in 0..len37 {
                                let base = base37
                                    .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                                let e37 = {
                                    let l23 = *base.add(0).cast::<*mut u8>();
                                    let l24 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len25 = l24;
                                    let bytes25 = _rt::Vec::from_raw_parts(
                                        l23.cast(),
                                        len25,
                                        len25,
                                    );
                                    let l26 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l27 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len28 = l27;
                                    let bytes28 = _rt::Vec::from_raw_parts(
                                        l26.cast(),
                                        len28,
                                        len28,
                                    );
                                    let l29 = i32::from(
                                        *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    let l33 = i32::from(
                                        *base
                                            .add(7 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    super::super::super::super::exports::scheduler::core_libs::types::ExportDef {
                                        export_type: _rt::string_lift(bytes25),
                                        name: _rt::string_lift(bytes28),
                                        scope: match l29 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l30 = *base
                                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l31 = *base
                                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let len32 = l31;
                                                    let bytes32 = _rt::Vec::from_raw_parts(
                                                        l30.cast(),
                                                        len32,
                                                        len32,
                                                    );
                                                    _rt::string_lift(bytes32)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        default_value: match l33 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l34 = *base
                                                        .add(8 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l35 = *base
                                                        .add(9 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let len36 = l35;
                                                    let bytes36 = _rt::Vec::from_raw_parts(
                                                        l34.cast(),
                                                        len36,
                                                        len36,
                                                    );
                                                    _rt::string_lift(bytes36)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    }
                                };
                                result37.push(e37);
                            }
                            _rt::cabi_dealloc(
                                base37,
                                len37 * (10 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            super::super::super::super::exports::scheduler::core_libs::types::ActionDef {
                                id: _rt::string_lift(bytes14),
                                call: _rt::string_lift(bytes17),
                                with_params: _rt::string_lift(bytes20),
                                exports: result37,
                            }
                        };
                        result38.push(e38);
                    }
                    _rt::cabi_dealloc(
                        base38,
                        len38 * (8 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let base61 = arg8;
                    let len61 = arg9;
                    let mut result61 = _rt::Vec::with_capacity(len61);
                    for i in 0..len61 {
                        let base = base61
                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                        let e61 = {
                            let l39 = *base.add(0).cast::<*mut u8>();
                            let l40 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len41 = l40;
                            let bytes41 = _rt::Vec::from_raw_parts(
                                l39.cast(),
                                len41,
                                len41,
                            );
                            let l42 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l43 = i32::from(
                                *base
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l47 = *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l48 = *base
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base60 = l47;
                            let len60 = l48;
                            let mut result60 = _rt::Vec::with_capacity(len60);
                            for i in 0..len60 {
                                let base = base60
                                    .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                                let e60 = {
                                    let l49 = *base.add(0).cast::<*mut u8>();
                                    let l50 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len51 = l50;
                                    let bytes51 = _rt::Vec::from_raw_parts(
                                        l49.cast(),
                                        len51,
                                        len51,
                                    );
                                    let l52 = i32::from(
                                        *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    let l56 = i32::from(
                                        *base
                                            .add(5 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    super::super::super::super::exports::scheduler::core_libs::types::WorkflowEdge {
                                        to: _rt::string_lift(bytes51),
                                        condition: match l52 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l53 = *base
                                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l54 = *base
                                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let len55 = l54;
                                                    let bytes55 = _rt::Vec::from_raw_parts(
                                                        l53.cast(),
                                                        len55,
                                                        len55,
                                                    );
                                                    _rt::string_lift(bytes55)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        label: match l56 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l57 = *base
                                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l58 = *base
                                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let len59 = l58;
                                                    let bytes59 = _rt::Vec::from_raw_parts(
                                                        l57.cast(),
                                                        len59,
                                                        len59,
                                                    );
                                                    _rt::string_lift(bytes59)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    }
                                };
                                result60.push(e60);
                            }
                            _rt::cabi_dealloc(
                                base60,
                                len60 * (8 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            super::super::super::super::exports::scheduler::core_libs::types::WorkflowNode {
                                id: _rt::string_lift(bytes41),
                                node_type: super::super::super::super::exports::scheduler::core_libs::types::NodeType::_lift(
                                    l42 as u8,
                                ),
                                action: match l43 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l44 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l45 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len46 = l45;
                                            let bytes46 = _rt::Vec::from_raw_parts(
                                                l44.cast(),
                                                len46,
                                                len46,
                                            );
                                            _rt::string_lift(bytes46)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                edges: result60,
                            }
                        };
                        result61.push(e61);
                    }
                    _rt::cabi_dealloc(
                        base61,
                        len61 * (8 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result62 = T::validate_scenario(super::super::super::super::exports::scheduler::core_libs::types::Scenario {
                        version: _rt::string_lift(bytes0),
                        name: _rt::string_lift(bytes1),
                        resources: result11,
                        actions: result38,
                        nodes: result61,
                    });
                    let ptr63 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result62 {
                        Ok(_) => {
                            *ptr63.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr63.add(0).cast::<u8>() = (1i32) as u8;
                            let vec64 = (e.into_bytes()).into_boxed_slice();
                            let ptr64 = vec64.as_ptr().cast::<u8>();
                            let len64 = vec64.len();
                            ::core::mem::forget(vec64);
                            *ptr63
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len64;
                            *ptr63
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr64.cast_mut();
                        }
                    };
                    ptr63
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_validate_scenario<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn parse_scenario(
                        yaml: _rt::String,
                    ) -> Result<Scenario, _rt::String>;
                    fn validate_scenario(scenario: Scenario) -> Result<(), _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_scheduler_core_libs_parser_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "scheduler:core-libs/parser@0.1.0#parse-scenario")] unsafe extern
                        "C" fn export_parse_scenario(arg0 : * mut u8, arg1 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_parse_scenario_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_scheduler:core-libs/parser@0.1.0#parse-scenario")]
                        unsafe extern "C" fn _post_return_parse_scenario(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_parse_scenario::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "scheduler:core-libs/parser@0.1.0#validate-scenario")] unsafe
                        extern "C" fn export_validate_scenario(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8, arg5 :
                        usize, arg6 : * mut u8, arg7 : usize, arg8 : * mut u8, arg9 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_validate_scenario_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9) } } #[unsafe (export_name =
                        "cabi_post_scheduler:core-libs/parser@0.1.0#validate-scenario")]
                        unsafe extern "C" fn _post_return_validate_scenario(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_validate_scenario::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_core_libs_parser_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 11 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 11
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_scheduler_core_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::scheduler::core_libs::types::__export_scheduler_core_libs_types_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::scheduler::core_libs::types);
        $($path_to_types_root)*::
        exports::scheduler::core_libs::parser::__export_scheduler_core_libs_parser_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::scheduler::core_libs::parser);
    };
}
#[doc(inline)]
pub(crate) use __export_scheduler_core_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:scheduler:core-libs@0.1.0:scheduler-core:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 738] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xdd\x04\x01A\x02\x01\
A\x05\x01B\x14\x01r\x03\x02ids\x0dresource-types\x0apropertiess\x04\0\x0cresourc\
e-def\x03\0\0\x01ks\x01r\x04\x0bexport-types\x04names\x05scope\x02\x0ddefault-va\
lue\x02\x04\0\x0aexport-def\x03\0\x03\x01p\x04\x01r\x04\x02ids\x04calls\x0bwith-\
paramss\x07exports\x05\x04\0\x0aaction-def\x03\0\x06\x01m\x02\x06action\x03end\x04\
\0\x09node-type\x03\0\x08\x01r\x03\x02tos\x09condition\x02\x05label\x02\x04\0\x0d\
workflow-edge\x03\0\x0a\x01p\x0b\x01r\x04\x02ids\x09node-type\x09\x06action\x02\x05\
edges\x0c\x04\0\x0dworkflow-node\x03\0\x0d\x01p\x01\x01p\x07\x01p\x0e\x01r\x05\x07\
versions\x04names\x09resources\x0f\x07actions\x10\x05nodes\x11\x04\0\x08scenario\
\x03\0\x12\x04\0\x1fscheduler:core-libs/types@0.1.0\x05\0\x02\x03\0\0\x08scenari\
o\x01B\x08\x02\x03\x02\x01\x01\x04\0\x08scenario\x03\0\0\x01j\x01\x01\x01s\x01@\x01\
\x04yamls\0\x02\x04\0\x0eparse-scenario\x01\x03\x01j\0\x01s\x01@\x01\x08scenario\
\x01\0\x04\x04\0\x11validate-scenario\x01\x05\x04\0\x20scheduler:core-libs/parse\
r@0.1.0\x05\x02\x04\0(scheduler:core-libs/scheduler-core@0.1.0\x04\0\x0b\x14\x01\
\0\x0escheduler-core\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-comp\
onent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
