// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod scheduler {
        pub mod actions_http {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct ExportDef {
                    pub export_type: _rt::String,
                    pub name: _rt::String,
                    pub scope: Option<_rt::String>,
                    pub default_value: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ExportDef {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExportDef")
                            .field("export-type", &self.export_type)
                            .field("name", &self.name)
                            .field("scope", &self.scope)
                            .field("default-value", &self.default_value)
                            .finish()
                    }
                }
                /// Re-export types from executor
                #[derive(Clone)]
                pub struct ActionDef {
                    pub id: _rt::String,
                    pub call: _rt::String,
                    pub with_params: _rt::String,
                    pub exports: _rt::Vec<ExportDef>,
                }
                impl ::core::fmt::Debug for ActionDef {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ActionDef")
                            .field("id", &self.id)
                            .field("call", &self.call)
                            .field("with-params", &self.with_params)
                            .field("exports", &self.exports)
                            .finish()
                    }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum ActionStatus {
                    Success,
                    Failed,
                }
                impl ::core::fmt::Debug for ActionStatus {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ActionStatus::Success => {
                                f.debug_tuple("ActionStatus::Success").finish()
                            }
                            ActionStatus::Failed => {
                                f.debug_tuple("ActionStatus::Failed").finish()
                            }
                        }
                    }
                }
                impl ActionStatus {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> ActionStatus {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => ActionStatus::Success,
                            1 => ActionStatus::Failed,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[derive(Clone)]
                pub struct ActionOutcome {
                    pub status: ActionStatus,
                    pub detail: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ActionOutcome {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ActionOutcome")
                            .field("status", &self.status)
                            .field("detail", &self.detail)
                            .finish()
                    }
                }
                #[doc(hidden)]
                macro_rules! __export_scheduler_actions_http_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_actions_http_types_0_1_0_cabi;
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod http_component {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ActionDef = super::super::super::super::exports::scheduler::actions_http::types::ActionDef;
                pub type ActionOutcome = super::super::super::super::exports::scheduler::actions_http::types::ActionOutcome;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_component_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::init_component();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init_component<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_do_http_action_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                    let base17 = arg6;
                    let len17 = arg7;
                    let mut result17 = _rt::Vec::with_capacity(len17);
                    for i in 0..len17 {
                        let base = base17
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        let e17 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = i32::from(
                                *base
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l13 = i32::from(
                                *base
                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            super::super::super::super::exports::scheduler::actions_http::types::ExportDef {
                                export_type: _rt::string_lift(bytes5),
                                name: _rt::string_lift(bytes8),
                                scope: match l9 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l10 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l11 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len12 = l11;
                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                l10.cast(),
                                                len12,
                                                len12,
                                            );
                                            _rt::string_lift(bytes12)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                default_value: match l13 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l14 = *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l15 = *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len16 = l15;
                                            let bytes16 = _rt::Vec::from_raw_parts(
                                                l14.cast(),
                                                len16,
                                                len16,
                                            );
                                            _rt::string_lift(bytes16)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result17.push(e17);
                    }
                    _rt::cabi_dealloc(
                        base17,
                        len17 * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result18 = T::do_http_action(super::super::super::super::exports::scheduler::actions_http::types::ActionDef {
                        id: _rt::string_lift(bytes0),
                        call: _rt::string_lift(bytes1),
                        with_params: _rt::string_lift(bytes2),
                        exports: result17,
                    });
                    let ptr19 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result18 {
                        Ok(e) => {
                            *ptr19.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::exports::scheduler::actions_http::types::ActionOutcome {
                                status: status20,
                                detail: detail20,
                            } = e;
                            *ptr19
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (status20.clone() as i32) as u8;
                            match detail20 {
                                Some(e) => {
                                    *ptr19
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec21 = (e.into_bytes()).into_boxed_slice();
                                    let ptr21 = vec21.as_ptr().cast::<u8>();
                                    let len21 = vec21.len();
                                    ::core::mem::forget(vec21);
                                    *ptr19
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len21;
                                    *ptr19
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr21.cast_mut();
                                }
                                None => {
                                    *ptr19
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        Err(e) => {
                            *ptr19.add(0).cast::<u8>() = (1i32) as u8;
                            let vec22 = (e.into_bytes()).into_boxed_slice();
                            let ptr22 = vec22.as_ptr().cast::<u8>();
                            let len22 = vec22.len();
                            ::core::mem::forget(vec22);
                            *ptr19
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len22;
                            *ptr19
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr22.cast_mut();
                        }
                    };
                    ptr19
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_do_http_action<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_release_component_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::release_component();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_release_component<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn init_component() -> Result<(), _rt::String>;
                    fn do_http_action(
                        action: ActionDef,
                    ) -> Result<ActionOutcome, _rt::String>;
                    fn release_component() -> Result<(), _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_scheduler_actions_http_http_component_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "scheduler:actions-http/http-component@0.1.0#init-component")]
                        unsafe extern "C" fn export_init_component() -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_init_component_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_scheduler:actions-http/http-component@0.1.0#init-component")]
                        unsafe extern "C" fn _post_return_init_component(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_init_component::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "scheduler:actions-http/http-component@0.1.0#do-http-action")]
                        unsafe extern "C" fn export_do_http_action(arg0 : * mut u8, arg1
                        : usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8, arg5 :
                        usize, arg6 : * mut u8, arg7 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_do_http_action_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7) } } #[unsafe
                        (export_name =
                        "cabi_post_scheduler:actions-http/http-component@0.1.0#do-http-action")]
                        unsafe extern "C" fn _post_return_do_http_action(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_do_http_action::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "scheduler:actions-http/http-component@0.1.0#release-component")]
                        unsafe extern "C" fn export_release_component() -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_release_component_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_scheduler:actions-http/http-component@0.1.0#release-component")]
                        unsafe extern "C" fn _post_return_release_component(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_release_component::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_actions_http_http_component_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_http_action_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::scheduler::actions_http::types::__export_scheduler_actions_http_types_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::scheduler::actions_http::types);
        $($path_to_types_root)*::
        exports::scheduler::actions_http::http_component::__export_scheduler_actions_http_http_component_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::scheduler::actions_http::http_component);
    };
}
#[doc(inline)]
pub(crate) use __export_http_action_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:scheduler:actions-http@0.1.0:http-action-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 656] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x84\x04\x01A\x02\x01\
A\x06\x01B\x0a\x01ks\x01r\x04\x0bexport-types\x04names\x05scope\0\x0ddefault-val\
ue\0\x04\0\x0aexport-def\x03\0\x01\x01p\x02\x01r\x04\x02ids\x04calls\x0bwith-par\
amss\x07exports\x03\x04\0\x0aaction-def\x03\0\x04\x01m\x02\x07success\x06failed\x04\
\0\x0daction-status\x03\0\x06\x01r\x02\x06status\x07\x06detail\0\x04\0\x0eaction\
-outcome\x03\0\x08\x04\0\"scheduler:actions-http/types@0.1.0\x05\0\x02\x03\0\0\x0a\
action-def\x02\x03\0\0\x0eaction-outcome\x01B\x0b\x02\x03\x02\x01\x01\x04\0\x0aa\
ction-def\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0eaction-outcome\x03\0\x02\x01j\0\x01\
s\x01@\0\0\x04\x04\0\x0einit-component\x01\x05\x01j\x01\x03\x01s\x01@\x01\x06act\
ion\x01\0\x06\x04\0\x0edo-http-action\x01\x07\x04\0\x11release-component\x01\x05\
\x04\0+scheduler:actions-http/http-component@0.1.0\x05\x03\x04\02scheduler:actio\
ns-http/http-action-component@0.1.0\x04\0\x0b\x1b\x01\0\x15http-action-component\
\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10\
wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
