use std::{
    path::{Path, PathBuf},
    process::Stdio,
    time::{SystemTime, UNIX_EPOCH},
};

use axum::{Json, extract::State, http::StatusCode, response::IntoResponse};
use serde::{Deserialize, Serialize};
use serde_yaml::Value as YamlValue;
use tokio::fs;
use tokio::fs::OpenOptions;
use tokio::process::Command;

use crate::{
    respond::json_error,
    state::AppState,
    util::{
        looks_like_sha256_hex, run_bundle_dir, wasm_catalog_path, wasm_path,
        wasm_scheduler_composed_path,
    },
};

fn find_repo_root() -> Option<std::path::PathBuf> {
    // Prefer deriving from the backend executable path:
    //   <repo>/target/<profile>/ntx-backend
    if let Ok(exe) = std::env::current_exe() {
        let mut cur = exe.as_path();
        while let Some(parent) = cur.parent() {
            if cur.file_name().map(|n| n == "target").unwrap_or(false) {
                return Some(parent.to_path_buf());
            }
            cur = parent;
        }
    }

    // Fallback: walk up from cwd until we find Cargo.toml.
    let mut cur = std::env::current_dir().ok()?;
    loop {
        if cur.join("Cargo.toml").is_file() {
            return Some(cur);
        }
        if !cur.pop() {
            break;
        }
    }
    None
}

fn resolve_ntx_bin(raw: &str) -> String {
    let raw = raw.trim();
    if raw.is_empty() {
        return "ntx".to_string();
    }

    // If it's already an absolute path, just use it.
    let p = std::path::Path::new(raw);
    if p.is_absolute() {
        return raw.to_string();
    }

    // If it exists relative to current working directory, use it.
    if p.exists() {
        return raw.to_string();
    }

    // If it looks like a repo-relative path, resolve against repo root.
    if let Some(root) = find_repo_root() {
        let candidate = root.join(p);
        if candidate.exists() {
            return candidate.display().to_string();
        }
    }

    raw.to_string()
}

fn is_safe_id(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
}

fn config_bundle_dir(data_dir: &Path, name: &str) -> PathBuf {
    data_dir.join("config-bundles").join(name)
}

async fn ensure_parent_dir(path: &Path) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).await?;
    }
    Ok(())
}

fn yaml_mapping_mut(v: &mut YamlValue) -> &mut serde_yaml::Mapping {
    if !matches!(v, YamlValue::Mapping(_)) {
        *v = YamlValue::Mapping(serde_yaml::Mapping::new());
    }
    match v {
        YamlValue::Mapping(m) => m,
        _ => unreachable!(),
    }
}

fn yaml_set_string(root: &mut YamlValue, path: &[&str], value: String) {
    let mut cur = root;
    for (i, key) in path.iter().enumerate() {
        let is_last = i == path.len() - 1;
        let m = yaml_mapping_mut(cur);
        let k = YamlValue::String((*key).to_string());
        if is_last {
            m.insert(k, YamlValue::String(value));
            return;
        }

        if !m.contains_key(&k) {
            m.insert(k.clone(), YamlValue::Mapping(serde_yaml::Mapping::new()));
        }
        cur = m.get_mut(&k).expect("just inserted");
    }
}

fn to_abs_string(path: &Path) -> String {
    if path.is_absolute() {
        return path.display().to_string();
    }

    if let Some(root) = find_repo_root() {
        return root.join(path).display().to_string();
    }

    if let Ok(cwd) = std::env::current_dir() {
        return cwd.join(path).display().to_string();
    }

    path.display().to_string()
}

#[derive(Debug, Deserialize)]
pub struct CreateRunBundleReq {
    /// Optional bundle id. If omitted, backend generates one.
    #[serde(default)]
    pub id: Option<String>,

    /// Existing config bundle name under `${DATA_DIR}/config-bundles/<name>/`.
    pub config_bundle: String,

    /// Existing uploaded wasm sha256 (hex) under `${DATA_DIR}/wasm/<sha>.wasm`.
    pub wasm_sha256: String,

    /// Scenario YAML generated by the builder.
    pub scenario_yaml: String,
}

#[derive(Debug, Serialize)]
pub struct CreateRunBundleResp {
    pub id: String,
    pub dir: String,
    pub config_dir: String,
    pub scenario_yaml_path: String,
    pub wasm_path: String,
    pub catalog_path: String,
    pub scheduler_composed_wasm_path: String,
}

#[derive(Debug, Serialize)]
pub struct RunRunBundleResp {
    pub id: String,
    pub pid: u32,
    pub command: Vec<String>,
    pub run_dir: String,
    pub stdout_path: String,
    pub stderr_path: String,
}

#[derive(Debug, Serialize)]
pub struct RunBundleStatusResp {
    pub id: String,
    pub running: bool,
    pub pid: Option<u32>,
    pub exit_code: Option<i32>,
    pub command: Option<Vec<String>>,
    pub run_dir: String,
    pub stdout_path: String,
    pub stderr_path: String,
}

#[derive(Debug, Serialize)]
pub struct RunBundleStopResp {
    pub id: String,
    pub stopped: bool,
}

#[derive(Debug, Serialize)]
pub struct RunBundleLogsResp {
    pub id: String,
    pub stdout: String,
    pub stderr: String,
    pub stdout_path: String,
    pub stderr_path: String,
    pub truncated: bool,
}

async fn read_tail_string(path: &Path, max_bytes: usize) -> anyhow::Result<(String, bool)> {
    let bytes = match fs::read(path).await {
        Ok(b) => b,
        Err(e) => {
            // If file doesn't exist yet, treat as empty.
            if e.kind() == std::io::ErrorKind::NotFound {
                return Ok((String::new(), false));
            }
            return Err(e.into());
        }
    };
    if bytes.len() <= max_bytes {
        Ok((String::from_utf8_lossy(&bytes).to_string(), false))
    } else {
        let start = bytes.len() - max_bytes;
        Ok((String::from_utf8_lossy(&bytes[start..]).to_string(), true))
    }
}

async fn ensure_ntx_setcap(ntx_path: &Path) -> anyhow::Result<()> {
    // Check current caps (best effort; getcap might be missing in some envs).
    if let Ok(out) = Command::new("getcap").arg(ntx_path).output().await {
        if out.status.success() {
            let s = String::from_utf8_lossy(&out.stdout);
            if s.contains("cap_net_raw") && s.contains("cap_net_admin") && s.contains("=ep") {
                return Ok(());
            }
        }
    }

    // Apply required caps.
    let out = Command::new("setcap")
        .arg("cap_net_raw,cap_net_admin+ep")
        .arg(ntx_path)
        .output()
        .await?;

    if !out.status.success() {
        let stdout = String::from_utf8_lossy(&out.stdout);
        let stderr = String::from_utf8_lossy(&out.stderr);
        anyhow::bail!(
            "setcap failed (exit={}): {}{}{}",
            out.status,
            stdout.trim(),
            if stdout.trim().is_empty() || stderr.trim().is_empty() {
                ""
            } else {
                "\n"
            },
            stderr.trim(),
        );
    }

    Ok(())
}

pub async fn create_run_bundle(
    State(state): State<std::sync::Arc<AppState>>,
    Json(body): Json<CreateRunBundleReq>,
) -> impl IntoResponse {
    let config_bundle = body.config_bundle.trim().to_string();
    if !is_safe_id(&config_bundle) {
        return json_error(
            StatusCode::BAD_REQUEST,
            "invalid config_bundle (allowed: [A-Za-z0-9._-])",
        );
    }

    let wasm_sha256 = body.wasm_sha256.trim().to_lowercase();
    if !looks_like_sha256_hex(&wasm_sha256) {
        return json_error(
            StatusCode::BAD_REQUEST,
            "invalid wasm_sha256 (expected 64 hex chars)",
        );
    }

    let id = match body.id {
        Some(v) => v.trim().to_string(),
        None => {
            let ms = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis();
            format!("run-{ms}")
        }
    };
    if !is_safe_id(&id) {
        return json_error(
            StatusCode::BAD_REQUEST,
            "invalid id (allowed: [A-Za-z0-9._-])",
        );
    }

    let source_bundle_dir = config_bundle_dir(&state.data_dir, &config_bundle);
    if !fs::try_exists(&source_bundle_dir).await.unwrap_or(false) {
        return json_error(StatusCode::NOT_FOUND, "config bundle not found");
    }

    let source_wasm = wasm_path(&state.data_dir, &wasm_sha256);
    if !fs::try_exists(&source_wasm).await.unwrap_or(false) {
        return json_error(StatusCode::NOT_FOUND, "wasm not found (upload it first)");
    }

    let source_catalog = wasm_catalog_path(&state.data_dir, &wasm_sha256);
    if !fs::try_exists(&source_catalog).await.unwrap_or(false) {
        return json_error(
            StatusCode::NOT_FOUND,
            "catalog.json not found for this wasm (upload wasm with catalog generation enabled)",
        );
    }

    let source_composed = wasm_scheduler_composed_path(&state.data_dir, &wasm_sha256);
    if !fs::try_exists(&source_composed).await.unwrap_or(false) {
        return json_error(
            StatusCode::NOT_FOUND,
            "scheduler-composed.wasm not found for this wasm (ensure wac compose ran during upload/push)",
        );
    }

    let out_dir = run_bundle_dir(&state.data_dir, &id);
    if fs::try_exists(&out_dir).await.unwrap_or(false) {
        return json_error(StatusCode::CONFLICT, "run bundle id already exists");
    }

    // Create runnable layout aligned with `ntx --config <dir>` behavior.
    // run-bundles/<id>/
    //   config/
    //     app.yaml            (rewritten to use absolute paths)
    //     config.yaml
    //     resource/resources.yaml
    //     scenario.yaml
    //   wasm/
    //     executor.wasm
    //     catalog.json
    //     scheduler-composed.wasm
    let out_config_dir = out_dir.join("config");
    let out_scenario = out_config_dir.join("scenario.yaml");
    let out_wasm = out_dir.join("wasm").join("executor.wasm");
    let out_catalog = out_dir.join("wasm").join("catalog.json");
    let out_composed = out_dir.join("wasm").join("scheduler-composed.wasm");

    if let Err(e) = fs::create_dir_all(&out_dir).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("create run bundle dir failed: {e}"),
        );
    }

    // Copy config files (explicit list keeps it simple and deterministic).
    // Source files:
    //   config/app.yaml
    //   config/config.yaml
    //   config/resource/resources.yaml
    let src_config_dir = source_bundle_dir.join("config");
    let src_app = src_config_dir.join("app.yaml");
    let src_cfg = src_config_dir.join("config.yaml");
    let src_res = src_config_dir.join("resource").join("resources.yaml");

    let dst_app = out_config_dir.join("app.yaml");
    let dst_cfg = out_config_dir.join("config.yaml");
    let dst_res = out_config_dir.join("resource").join("resources.yaml");

    for (src, dst, label) in [
        (src_app, dst_app, "app.yaml"),
        (src_cfg, dst_cfg, "config.yaml"),
        (src_res, dst_res, "resources.yaml"),
    ] {
        if !fs::try_exists(&src).await.unwrap_or(false) {
            return json_error(
                StatusCode::NOT_FOUND,
                format!("config bundle missing {label}"),
            );
        }
        if let Err(e) = ensure_parent_dir(&dst).await {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("create config dir failed: {e}"),
            );
        }
        if let Err(e) = fs::copy(&src, &dst).await {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("copy {label} failed: {e}"),
            );
        }
    }

    if let Err(e) = fs::write(&out_scenario, body.scenario_yaml).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write scenario.yaml failed: {e}"),
        );
    }

    if let Err(e) = ensure_parent_dir(&out_wasm).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("create wasm dir failed: {e}"),
        );
    }
    if let Err(e) = fs::copy(&source_wasm, &out_wasm).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("copy wasm failed: {e}"),
        );
    }

    if let Err(e) = fs::copy(&source_catalog, &out_catalog).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("copy catalog.json failed: {e}"),
        );
    }

    if let Err(e) = fs::copy(&source_composed, &out_composed).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("copy scheduler-composed.wasm failed: {e}"),
        );
    }

    // Rewrite app.yaml so users can run from anywhere:
    //   ntx --config <run-bundle-dir>
    // The host uses cfg.kernel.config_path and cfg.scheduler.wasm.* as-is.
    let dst_app = out_config_dir.join("app.yaml");
    let app_raw = match fs::read_to_string(&dst_app).await {
        Ok(s) => s,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("read packaged app.yaml failed: {e}"),
            );
        }
    };
    let mut app_yaml: YamlValue = match serde_yaml::from_str(&app_raw) {
        Ok(v) => v,
        Err(e) => {
            return json_error(
                StatusCode::BAD_REQUEST,
                format!("parse packaged app.yaml failed: {e}"),
            );
        }
    };

    yaml_set_string(
        &mut app_yaml,
        &["kernel", "config_path"],
        to_abs_string(&out_config_dir.join("config.yaml")),
    );
    yaml_set_string(
        &mut app_yaml,
        &["scheduler", "wasm", "component_path"],
        to_abs_string(&out_composed),
    );
    yaml_set_string(
        &mut app_yaml,
        &["scheduler", "wasm", "config_dir"],
        "config".to_string(),
    );

    let new_app_raw = match serde_yaml::to_string(&app_yaml) {
        Ok(s) => s,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("serialize app.yaml failed: {e}"),
            );
        }
    };
    if let Err(e) = fs::write(&dst_app, new_app_raw).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write packaged app.yaml failed: {e}"),
        );
    }

    // Rewrite config.yaml resource path to be absolute as well.
    // Some configs use relative paths like "config/resource/resources.yaml".
    // Make it robust regardless of process cwd.
    let dst_cfg = out_config_dir.join("config.yaml");
    let cfg_raw = match fs::read_to_string(&dst_cfg).await {
        Ok(s) => s,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("read packaged config.yaml failed: {e}"),
            );
        }
    };
    let mut cfg_yaml: YamlValue = match serde_yaml::from_str(&cfg_raw) {
        Ok(v) => v,
        Err(e) => {
            return json_error(
                StatusCode::BAD_REQUEST,
                format!("parse packaged config.yaml failed: {e}"),
            );
        }
    };
    yaml_set_string(
        &mut cfg_yaml,
        &["resource", "path"],
        to_abs_string(&out_config_dir.join("resource").join("resources.yaml")),
    );
    let new_cfg_raw = match serde_yaml::to_string(&cfg_yaml) {
        Ok(s) => s,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("serialize config.yaml failed: {e}"),
            );
        }
    };
    if let Err(e) = fs::write(&dst_cfg, new_cfg_raw).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("write packaged config.yaml failed: {e}"),
        );
    }

    (
        StatusCode::OK,
        Json(CreateRunBundleResp {
            id: id.clone(),
            dir: out_dir.display().to_string(),
            config_dir: out_config_dir.display().to_string(),
            scenario_yaml_path: out_scenario.display().to_string(),
            wasm_path: out_wasm.display().to_string(),
            catalog_path: out_catalog.display().to_string(),
            scheduler_composed_wasm_path: out_composed.display().to_string(),
        }),
    )
        .into_response()
}

pub async fn run_run_bundle(
    State(state): State<std::sync::Arc<AppState>>,
    axum::extract::Path(id): axum::extract::Path<String>,
) -> impl IntoResponse {
    let id = id.trim().to_string();
    if !is_safe_id(&id) {
        return json_error(
            StatusCode::BAD_REQUEST,
            "invalid id (allowed: [A-Za-z0-9._-])",
        );
    }

    let run_dir = run_bundle_dir(&state.data_dir, &id);
    if !fs::try_exists(&run_dir).await.unwrap_or(false) {
        return json_error(StatusCode::NOT_FOUND, "run bundle not found");
    }

    // Ntx accepts either a config file path or a directory; when we also set
    // `current_dir` to `run_dir`, a relative `--config` argument would resolve
    // relative to `run_dir` (and likely break). Always pass an absolute path.
    let run_dir_abs: PathBuf = std::fs::canonicalize(&run_dir).unwrap_or_else(|_| run_dir.clone());

    // If already running, return a conflict.
    {
        let mut procs = state.run_processes.lock().await;
        if let Some(existing) = procs.get_mut(&id) {
            match existing.child.try_wait() {
                Ok(Some(_status)) => {
                    // Process already exited; allow re-run.
                    procs.remove(&id);
                }
                Ok(None) => {
                    return json_error(StatusCode::CONFLICT, "run bundle already running");
                }
                Err(e) => {
                    procs.remove(&id);
                    return json_error(
                        StatusCode::INTERNAL_SERVER_ERROR,
                        format!("check running process failed: {e}"),
                    );
                }
            }
        }
    }

    let log_dir = run_dir.join("logs");
    if let Err(e) = fs::create_dir_all(&log_dir).await {
        return json_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("create logs dir failed: {e}"),
        );
    }
    let stdout_path = log_dir.join("ntx.stdout.log");
    let stderr_path = log_dir.join("ntx.stderr.log");

    let stdout_file = match OpenOptions::new()
        .create(true)
        .append(true)
        .open(&stdout_path)
        .await
    {
        Ok(f) => f,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("open stdout log failed: {e}"),
            );
        }
    };
    let stderr_file = match OpenOptions::new()
        .create(true)
        .append(true)
        .open(&stderr_path)
        .await
    {
        Ok(f) => f,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("open stderr log failed: {e}"),
            );
        }
    };

    let stdout_std = stdout_file.into_std().await;
    let stderr_std = stderr_file.into_std().await;

    // Resolve `ntx` binary path.
    // If `ntx` is not on PATH (common in dev), prefer a repo-local build output.
    let resolved_ntx_bin = if state.ntx_bin == "ntx" {
        let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
        let cand_debug_lower = cwd.join("target").join("debug").join("ntx");
        let cand_debug_upper = cwd.join("target").join("debug").join("Ntx");
        let cand_release_lower = cwd.join("target").join("release").join("ntx");
        let cand_release_upper = cwd.join("target").join("release").join("Ntx");
        if cand_debug_lower.exists() {
            cand_debug_lower.display().to_string()
        } else if cand_debug_upper.exists() {
            cand_debug_upper.display().to_string()
        } else if cand_release_lower.exists() {
            cand_release_lower.display().to_string()
        } else if cand_release_upper.exists() {
            cand_release_upper.display().to_string()
        } else {
            state.ntx_bin.clone()
        }
    } else {
        state.ntx_bin.clone()
    };

    // Ensure required capabilities for AF_PACKET execution.
    // Note: this will only succeed if the backend process has privilege to call setcap.
    let resolved_path = std::path::Path::new(&resolved_ntx_bin);
    if resolved_path.exists() {
        if let Err(e) = ensure_ntx_setcap(resolved_path).await {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!(
                    "failed to setcap on ntx binary ({}): {e}. Hint: run backend as root, or run `sudo setcap cap_net_raw,cap_net_admin+ep {}` once",
                    resolved_path.display(),
                    resolved_path.display(),
                ),
            );
        }
    }

    let cmd_vec = vec![
        resolved_ntx_bin.clone(),
        "--config".to_string(),
        run_dir_abs.display().to_string(),
    ];

    let mut cmd = Command::new(&resolved_ntx_bin);
    cmd.arg("--config")
        .arg(&run_dir_abs)
        .current_dir(&run_dir_abs)
        .stdout(Stdio::from(stdout_std))
        .stderr(Stdio::from(stderr_std));

    let child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!(
                    "spawn ntx failed: {e}. Hint: set backend `ntx_bin` (crates/ntx-backend/conf/ntx-backend.yaml) or start backend with `--ntx-bin /abs/path/to/ntx`",
                ),
            );
        }
    };

    let pid = match child.id() {
        Some(pid) => pid,
        None => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "spawned process had no pid",
            );
        }
    };

    {
        let mut procs = state.run_processes.lock().await;
        procs.insert(
            id.clone(),
            crate::state::RunProcess {
                child,
                run_dir: run_dir.clone(),
                command: cmd_vec.clone(),
                stdout_path: stdout_path.clone(),
                stderr_path: stderr_path.clone(),
            },
        );
    }

    (
        StatusCode::OK,
        Json(RunRunBundleResp {
            id,
            pid,
            command: cmd_vec,
            run_dir: run_dir.display().to_string(),
            stdout_path: stdout_path.display().to_string(),
            stderr_path: stderr_path.display().to_string(),
        }),
    )
        .into_response()
}

pub async fn get_run_bundle_status(
    State(state): State<std::sync::Arc<AppState>>,
    axum::extract::Path(id): axum::extract::Path<String>,
) -> impl IntoResponse {
    let id = id.trim().to_string();
    if !is_safe_id(&id) {
        return json_error(
            StatusCode::BAD_REQUEST,
            "invalid id (allowed: [A-Za-z0-9._-])",
        );
    }

    let run_dir = run_bundle_dir(&state.data_dir, &id);
    if !fs::try_exists(&run_dir).await.unwrap_or(false) {
        return json_error(StatusCode::NOT_FOUND, "run bundle not found");
    }

    let stdout_path = run_dir.join("logs").join("ntx.stdout.log");
    let stderr_path = run_dir.join("logs").join("ntx.stderr.log");

    let mut procs = state.run_processes.lock().await;
    if let Some(mut proc) = procs.remove(&id) {
        match proc.child.try_wait() {
            Ok(Some(status)) => {
                let exit_code = status.code();
                return (
                    StatusCode::OK,
                    Json(RunBundleStatusResp {
                        id,
                        running: false,
                        pid: None,
                        exit_code,
                        command: Some(proc.command),
                        run_dir: run_dir.display().to_string(),
                        stdout_path: proc.stdout_path.display().to_string(),
                        stderr_path: proc.stderr_path.display().to_string(),
                    }),
                )
                    .into_response();
            }
            Ok(None) => {
                let pid = proc.child.id();
                let command = proc.command.clone();
                let stdout_path = proc.stdout_path.clone();
                let stderr_path = proc.stderr_path.clone();
                procs.insert(id.clone(), proc);
                return (
                    StatusCode::OK,
                    Json(RunBundleStatusResp {
                        id,
                        running: true,
                        pid,
                        exit_code: None,
                        command: Some(command),
                        run_dir: run_dir.display().to_string(),
                        stdout_path: stdout_path.display().to_string(),
                        stderr_path: stderr_path.display().to_string(),
                    }),
                )
                    .into_response();
            }
            Err(e) => {
                return json_error(
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!("check running process failed: {e}"),
                );
            }
        }
    }

    // Not tracked in memory => not running (or started elsewhere).
    (
        StatusCode::OK,
        Json(RunBundleStatusResp {
            id,
            running: false,
            pid: None,
            exit_code: None,
            command: None,
            run_dir: run_dir.display().to_string(),
            stdout_path: stdout_path.display().to_string(),
            stderr_path: stderr_path.display().to_string(),
        }),
    )
        .into_response()
}

pub async fn stop_run_bundle(
    State(state): State<std::sync::Arc<AppState>>,
    axum::extract::Path(id): axum::extract::Path<String>,
) -> impl IntoResponse {
    let id = id.trim().to_string();
    if !is_safe_id(&id) {
        return json_error(
            StatusCode::BAD_REQUEST,
            "invalid id (allowed: [A-Za-z0-9._-])",
        );
    }

    let mut procs = state.run_processes.lock().await;
    let Some(mut proc) = procs.remove(&id) else {
        return (
            StatusCode::OK,
            Json(RunBundleStopResp { id, stopped: false }),
        )
            .into_response();
    };

    let _ = proc.child.kill().await;
    (
        StatusCode::OK,
        Json(RunBundleStopResp { id, stopped: true }),
    )
        .into_response()
}

pub async fn get_run_bundle_logs(
    State(state): State<std::sync::Arc<AppState>>,
    axum::extract::Path(id): axum::extract::Path<String>,
) -> impl IntoResponse {
    let id = id.trim().to_string();
    if !is_safe_id(&id) {
        return json_error(
            StatusCode::BAD_REQUEST,
            "invalid id (allowed: [A-Za-z0-9._-])",
        );
    }

    let run_dir = run_bundle_dir(&state.data_dir, &id);
    if !fs::try_exists(&run_dir).await.unwrap_or(false) {
        return json_error(StatusCode::NOT_FOUND, "run bundle not found");
    }

    // Prefer tracked paths (if process was started via this backend).
    let (stdout_path, stderr_path) = {
        let procs = state.run_processes.lock().await;
        if let Some(proc) = procs.get(&id) {
            (proc.stdout_path.clone(), proc.stderr_path.clone())
        } else {
            (
                run_dir.join("logs").join("ntx.stdout.log"),
                run_dir.join("logs").join("ntx.stderr.log"),
            )
        }
    };

    let max_bytes = 20_000usize;
    let (stdout, t1) = match read_tail_string(&stdout_path, max_bytes).await {
        Ok(v) => v,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("read stdout logs failed: {e}"),
            );
        }
    };
    let (stderr, t2) = match read_tail_string(&stderr_path, max_bytes).await {
        Ok(v) => v,
        Err(e) => {
            return json_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("read stderr logs failed: {e}"),
            );
        }
    };

    (
        StatusCode::OK,
        Json(RunBundleLogsResp {
            id,
            stdout,
            stderr,
            stdout_path: stdout_path.display().to_string(),
            stderr_path: stderr_path.display().to_string(),
            truncated: t1 || t2,
        }),
    )
        .into_response()
}
