package scheduler:main;

use scheduler:actions-executor/action-component@0.1.0;
use scheduler:event-bus/event-bus@0.1.0;

world scheduler-component {
    import action-component;
    import event-bus;
    export run: func(dir: string) -> result<_, string>;  // dir 表示配置文件的路径
}
