package scheduler:main;

use scheduler:actions-http/http-component@0.1.0;
use scheduler:executor-types/types@0.1.0 as exec-types;

world scheduler-component {
    import http-component;
    export exec-types;
    export run-scenario: func(scenario-yaml: string) -> result<string, string>;
}
