// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_run_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::run();
}
pub trait Guest {
    fn run() -> ();
}
#[doc(hidden)]
macro_rules! __export_world_guest_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "run")] unsafe extern "C" fn
        export_run() { unsafe { $($path_to_types)*:: _export_run_cabi::<$ty > () } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_guest_cabi;
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod afxdp {
        pub mod demo {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod packet {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct PacketMeta {
                    pub frame_len: u32,
                    pub rx_queue: u32,
                }
                impl ::core::fmt::Debug for PacketMeta {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("PacketMeta")
                            .field("frame-len", &self.frame_len)
                            .field("rx-queue", &self.rx_queue)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_packet_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: *mut u8,
                    arg3: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg3;
                    T::on_packet(
                        PacketMeta {
                            frame_len: arg0 as u32,
                            rx_queue: arg1 as u32,
                        },
                        _rt::Vec::from_raw_parts(arg2.cast(), len0, len0),
                    );
                }
                pub trait Guest {
                    fn on_packet(meta: PacketMeta, data: _rt::Vec<u8>) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_afxdp_demo_packet_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "afxdp:demo/packet#on-packet")] unsafe extern "C" fn
                        export_on_packet(arg0 : i32, arg1 : i32, arg2 : * mut u8, arg3 :
                        usize,) { unsafe { $($path_to_types)*::
                        _export_on_packet_cabi::<$ty > (arg0, arg1, arg2, arg3) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_afxdp_demo_packet_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_guest_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_guest_cabi!($ty with_types_in
        $($path_to_types_root)*); $($path_to_types_root)*::
        exports::afxdp::demo::packet::__export_afxdp_demo_packet_cabi!($ty with_types_in
        $($path_to_types_root)*:: exports::afxdp::demo::packet);
    };
}
#[doc(inline)]
pub(crate) use __export_guest_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:afxdp:demo:guest:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 264] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8c\x01\x01A\x02\x01\
A\x04\x01@\0\x01\0\x04\0\x03run\x01\0\x01B\x05\x01r\x02\x09frame-leny\x08rx-queu\
ey\x04\0\x0bpacket-meta\x03\0\0\x01p}\x01@\x02\x04meta\x01\x04data\x02\x01\0\x04\
\0\x09on-packet\x01\x03\x04\0\x11afxdp:demo/packet\x05\x01\x04\0\x10afxdp:demo/g\
uest\x04\0\x0b\x0b\x01\0\x05guest\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\
\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
