package component:tcp-client;
use wasi:sockets/tcp-create-socket@0.2.6;
use wasi:sockets/tcp@0.2.6;
use wasi:sockets/network@0.2.6;
use wasi:sockets/instance-network@0.2.6;
use wasi:cli/environment@0.2.6;
use wasi:cli/exit@0.2.6;
use wasi:cli/stderr@0.2.6;
use wasi:cli/stdout@0.2.6;
use wasi:io/error@0.2.6;
use wasi:io/streams@0.2.6;

interface logging {
    enum level {
        debug,
        info,
        error,
    }
    log: func(level: level, msg: string);
}

interface config {
    resource config {
        constructor();
        get-config: func() -> string;
    }
}

interface respool {
    resource script {
        constructor();
    }
}

interface protocol {
    use config.{config};
    type handler = u32;
    resource protocol-tcp-client {
        constructor(name: string);
        register: func(res: option<u32>, config: option<u32>) -> handler;
        init: func();
        do-action: func();
        release: func();
        un-register: func();
    }
}

interface sock {
    resource sock {
        constructor(name: string);
        newsock: func(sock-type: u32) -> u32;
        bind: func(id: u32, ip: string, port: u16);
        send: func(id: u32, data: list<u8>);
        recv: func(id: u32, len: u32) -> list<u8>;
        close: func(id: u32);
    }
}

world tcp-client {
    import environment;
    import exit;
    import stderr;
    import stdout;
    import error;
    import streams;

    import respool;
    import logging;
    import sock;
    export protocol;
}

world core {
    import tcp-create-socket;
    import tcp;
    import network;
    import instance-network;
    import environment;
    import exit;
    import stderr;
    import stdout;
    import error;
    import streams;
    export sock;
    export logging;
    export config;
    export respool;
}

world demo {
    import environment;
    import exit;
    import stderr;
    import stdout;
    import error;
    import streams;
    import protocol;
    import respool;
    import logging;
    import sock;
    export start: func();
}