package component:tcp-client;
use wasi:sockets/tcp-create-socket@0.2.8;
use wasi:sockets/tcp@0.2.8;
use wasi:sockets/network@0.2.8;
use wasi:sockets/instance-network@0.2.8;

interface logging {
    enum level {
        debug,
        info,
        error,
    }
    log: func(level: level, msg: string);
}

interface config {
    resource config {
        constructor();
        get-config: func() -> string;
    }
}

interface respool {
    resource script {
        constructor();
    }
}

interface flow {
    record action {
        id: u32,
    }
    record control {
        id: u32,
    }
    enum status {
        success,
        failure,
    }
    record workbook {
        actions: list<action>,
        control: control,
        status: status,
    }
    resource res {
        constructor();
        execute: func(wb: workbook) -> workbook;
    }
}

interface protocol {
    use flow.{res, action};
    use respool.{script};
    use config.{config};
    type handler = u32;
    resource protocol-tcp-client {
        constructor(name: string);
        register: func(res: res, config: config) -> handler;
        init: func();
        do-action: func();
        release: func();
        un-register: func();
    }
}
interface sock {
    resource sock {
        constructor();
        newsock: func(sock-type: u32) -> u32;
        bind: func(id: u32, ip: string, port: u16);
        send: func(id: u32, data: list<u8>);
        recv: func(id: u32) -> list<u8>;
    }
}
world tcp-client {
    import logging;
    // import sock;
    export protocol;
}

world core {
    import protocol;
    import tcp-create-socket;
    import tcp;
    import network;
    import instance-network;

    export sock;
    export logging;
    export config;
    export flow;
    export respool;
}

world demo {
    import protocol;
    export start: func();
}