// Generated by `wit-bindgen` 0.48.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod scheduler {
    pub mod core_libs {

        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod socket {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() =
                super::super::super::__link_custom_section_describing_imports;

            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum AddressFamily {
                Ipv4,
                Ipv6,
            }
            impl ::core::fmt::Debug for AddressFamily {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        AddressFamily::Ipv4 => f.debug_tuple("AddressFamily::Ipv4").finish(),
                        AddressFamily::Ipv6 => f.debug_tuple("AddressFamily::Ipv6").finish(),
                    }
                }
            }

            impl AddressFamily {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> AddressFamily {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }

                    match val {
                        0 => AddressFamily::Ipv4,
                        1 => AddressFamily::Ipv6,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum SocketProtocol {
                Tcp,
                Udp,
            }
            impl ::core::fmt::Debug for SocketProtocol {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        SocketProtocol::Tcp => f.debug_tuple("SocketProtocol::Tcp").finish(),
                        SocketProtocol::Udp => f.debug_tuple("SocketProtocol::Udp").finish(),
                    }
                }
            }

            impl SocketProtocol {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> SocketProtocol {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }

                    match val {
                        0 => SocketProtocol::Tcp,
                        1 => SocketProtocol::Udp,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[derive(Clone)]
            pub struct SocketAddress {
                pub host: _rt::String,
                pub port: u16,
            }
            impl ::core::fmt::Debug for SocketAddress {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("SocketAddress")
                        .field("host", &self.host)
                        .field("port", &self.port)
                        .finish()
                }
            }
            pub type SocketHandle = u32;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum SocketError {
                ConnectionRefused,
                ConnectionReset,
                ConnectionAborted,
                NetworkUnreachable,
                AddressInUse,
                AddressNotAvailable,
                Timeout,
                WouldBlock,
                InvalidInput,
                Other,
            }
            impl SocketError {
                pub fn name(&self) -> &'static str {
                    match self {
                        SocketError::ConnectionRefused => "connection-refused",
                        SocketError::ConnectionReset => "connection-reset",
                        SocketError::ConnectionAborted => "connection-aborted",
                        SocketError::NetworkUnreachable => "network-unreachable",
                        SocketError::AddressInUse => "address-in-use",
                        SocketError::AddressNotAvailable => "address-not-available",
                        SocketError::Timeout => "timeout",
                        SocketError::WouldBlock => "would-block",
                        SocketError::InvalidInput => "invalid-input",
                        SocketError::Other => "other",
                    }
                }
                pub fn message(&self) -> &'static str {
                    match self {
                        SocketError::ConnectionRefused => "",
                        SocketError::ConnectionReset => "",
                        SocketError::ConnectionAborted => "",
                        SocketError::NetworkUnreachable => "",
                        SocketError::AddressInUse => "",
                        SocketError::AddressNotAvailable => "",
                        SocketError::Timeout => "",
                        SocketError::WouldBlock => "",
                        SocketError::InvalidInput => "",
                        SocketError::Other => "",
                    }
                }
            }
            impl ::core::fmt::Debug for SocketError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("SocketError")
                        .field("code", &(*self as i32))
                        .field("name", &self.name())
                        .field("message", &self.message())
                        .finish()
                }
            }
            impl ::core::fmt::Display for SocketError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    write!(f, "{} (error {})", self.name(), *self as i32)
                }
            }

            impl ::core::error::Error for SocketError {}

            impl SocketError {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> SocketError {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }

                    match val {
                        0 => SocketError::ConnectionRefused,
                        1 => SocketError::ConnectionReset,
                        2 => SocketError::ConnectionAborted,
                        3 => SocketError::NetworkUnreachable,
                        4 => SocketError::AddressInUse,
                        5 => SocketError::AddressNotAvailable,
                        6 => SocketError::Timeout,
                        7 => SocketError::WouldBlock,
                        8 => SocketError::InvalidInput,
                        9 => SocketError::Other,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[allow(unused_unsafe, clippy::all)]
            #[allow(async_fn_in_trait)]
            pub fn create_socket(
                family: AddressFamily,
                protocol: SocketProtocol,
            ) -> Result<SocketHandle, SocketError> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "scheduler:core-libs/socket@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "create-socket"]
                        fn wit_import1(_: i32, _: i32, _: *mut u8);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i32, _: i32, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import1(family.clone() as i32, protocol.clone() as i32, ptr0);
                    let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                    let result5 = match l2 {
                        0 => {
                            let e = {
                                let l3 = *ptr0.add(4).cast::<i32>();

                                l3 as u32
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l4 = i32::from(*ptr0.add(4).cast::<u8>());

                                SocketError::_lift(l4 as u8)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            #[allow(async_fn_in_trait)]
            pub fn connect(
                socket: SocketHandle,
                address: &SocketAddress,
            ) -> Result<(), SocketError> {
                unsafe {
                    #[repr(align(1))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2]);
                    let SocketAddress {
                        host: host0,
                        port: port0,
                    } = address;
                    let vec1 = host0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "scheduler:core-libs/socket@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "connect"]
                        fn wit_import3(_: i32, _: *mut u8, _: usize, _: i32, _: *mut u8);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    wit_import3(
                        _rt::as_i32(socket),
                        ptr1.cast_mut(),
                        len1,
                        _rt::as_i32(port0),
                        ptr2,
                    );
                    let l4 = i32::from(*ptr2.add(0).cast::<u8>());
                    let result6 = match l4 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l5 = i32::from(*ptr2.add(1).cast::<u8>());

                                SocketError::_lift(l5 as u8)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result6
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            #[allow(async_fn_in_trait)]
            pub fn bind(socket: SocketHandle, address: &SocketAddress) -> Result<(), SocketError> {
                unsafe {
                    #[repr(align(1))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2]);
                    let SocketAddress {
                        host: host0,
                        port: port0,
                    } = address;
                    let vec1 = host0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "scheduler:core-libs/socket@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "bind"]
                        fn wit_import3(_: i32, _: *mut u8, _: usize, _: i32, _: *mut u8);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    wit_import3(
                        _rt::as_i32(socket),
                        ptr1.cast_mut(),
                        len1,
                        _rt::as_i32(port0),
                        ptr2,
                    );
                    let l4 = i32::from(*ptr2.add(0).cast::<u8>());
                    let result6 = match l4 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l5 = i32::from(*ptr2.add(1).cast::<u8>());

                                SocketError::_lift(l5 as u8)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result6
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            #[allow(async_fn_in_trait)]
            pub fn send(socket: SocketHandle, data: &[u8]) -> Result<u64, SocketError> {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                    let vec0 = data;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "scheduler:core-libs/socket@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "send"]
                        fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import2(_rt::as_i32(socket), ptr0.cast_mut(), len0, ptr1);
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result6 = match l3 {
                        0 => {
                            let e = {
                                let l4 = *ptr1.add(8).cast::<i64>();

                                l4 as u64
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l5 = i32::from(*ptr1.add(8).cast::<u8>());

                                SocketError::_lift(l5 as u8)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result6
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            #[allow(async_fn_in_trait)]
            pub fn receive(
                socket: SocketHandle,
                max_length: u64,
            ) -> Result<_rt::Vec<u8>, SocketError> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit();
                            3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "scheduler:core-libs/socket@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "receive"]
                        fn wit_import1(_: i32, _: i64, _: *mut u8);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import1(_rt::as_i32(socket), _rt::as_i64(&max_length), ptr0);
                    let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                    let result7 = match l2 {
                        0 => {
                            let e = {
                                let l3 = *ptr0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l4 = *ptr0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len5 = l4;

                                _rt::Vec::from_raw_parts(l3.cast(), len5, len5)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l6 = i32::from(
                                    *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );

                                SocketError::_lift(l6 as u8)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            #[allow(async_fn_in_trait)]
            pub fn close(socket: SocketHandle) -> Result<(), SocketError> {
                unsafe {
                    #[repr(align(1))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "scheduler:core-libs/socket@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "close"]
                        fn wit_import1(_: i32, _: *mut u8);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import1(_rt::as_i32(socket), ptr0);
                    let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                    let result4 = match l2 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l3 = i32::from(*ptr0.add(1).cast::<u8>());

                                SocketError::_lift(l3 as u8)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result4
                }
            }
        }

        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() =
                super::super::super::__link_custom_section_describing_imports;

            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct ResourceDef {
                pub id: _rt::String,
                pub resource_type: _rt::String,
                pub properties: _rt::String,
            }
            impl ::core::fmt::Debug for ResourceDef {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("ResourceDef")
                        .field("id", &self.id)
                        .field("resource-type", &self.resource_type)
                        .field("properties", &self.properties)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ExportDef {
                pub export_type: _rt::String,
                pub name: _rt::String,
                pub scope: Option<_rt::String>,
                pub default_value: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for ExportDef {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("ExportDef")
                        .field("export-type", &self.export_type)
                        .field("name", &self.name)
                        .field("scope", &self.scope)
                        .field("default-value", &self.default_value)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ActionDef {
                pub id: _rt::String,
                pub call: _rt::String,
                pub with_params: _rt::String,
                pub exports: _rt::Vec<ExportDef>,
            }
            impl ::core::fmt::Debug for ActionDef {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("ActionDef")
                        .field("id", &self.id)
                        .field("call", &self.call)
                        .field("with-params", &self.with_params)
                        .field("exports", &self.exports)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum NodeType {
                Action,
                End,
            }
            impl ::core::fmt::Debug for NodeType {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        NodeType::Action => f.debug_tuple("NodeType::Action").finish(),
                        NodeType::End => f.debug_tuple("NodeType::End").finish(),
                    }
                }
            }

            impl NodeType {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> NodeType {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }

                    match val {
                        0 => NodeType::Action,
                        1 => NodeType::End,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[derive(Clone)]
            pub struct WorkflowEdge {
                pub to: _rt::String,
                pub condition: Option<_rt::String>,
                pub label: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for WorkflowEdge {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("WorkflowEdge")
                        .field("to", &self.to)
                        .field("condition", &self.condition)
                        .field("label", &self.label)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct WorkflowNode {
                pub id: _rt::String,
                pub node_type: NodeType,
                pub action: Option<_rt::String>,
                pub edges: _rt::Vec<WorkflowEdge>,
            }
            impl ::core::fmt::Debug for WorkflowNode {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("WorkflowNode")
                        .field("id", &self.id)
                        .field("node-type", &self.node_type)
                        .field("action", &self.action)
                        .field("edges", &self.edges)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct Scenario {
                pub version: _rt::String,
                pub name: _rt::String,
                pub resources: _rt::Vec<ResourceDef>,
                pub actions: _rt::Vec<ActionDef>,
                pub nodes: _rt::Vec<WorkflowNode>,
            }
            impl ::core::fmt::Debug for Scenario {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Scenario")
                        .field("version", &self.version)
                        .field("name", &self.name)
                        .field("resources", &self.resources)
                        .field("actions", &self.actions)
                        .field("nodes", &self.nodes)
                        .finish()
                }
            }
        }
    }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod scheduler {
        pub mod actions_http {

            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod http_component {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type ActionDef = super::super::super::super::exports::scheduler::executor_types::types::ActionDef;
                pub type ActionOutcome = super::super::super::super::exports::scheduler::executor_types::types::ActionOutcome;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_init_component_cabi<T: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T::init_component() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result0 {
                            Ok(_) => {
                                *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            }
                            Err(e) => {
                                *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                                let vec2 = (e.into_bytes()).into_boxed_slice();
                                let ptr2 = vec2.as_ptr().cast::<u8>();
                                let len2 = vec2.len();
                                ::core::mem::forget(vec2);
                                *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len2;
                                *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr2.cast_mut();
                            }
                        };
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init_component<T: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => (),
                            _ => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_do_http_action_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result18 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            let len2 = arg5;
                            let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                            let base17 = arg6;
                            let len17 = arg7;
                            let mut result17 = _rt::Vec::with_capacity(len17);
                            for i in 0..len17 {
                                let base =
                                    base17.add(i * (10 * ::core::mem::size_of::<*const u8>()));
                                let e17 = {
                                    let l3 = *base.add(0).cast::<*mut u8>();
                                    let l4 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len5 = l4;
                                    let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                                    let l6 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len8 = l7;
                                    let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                                    let l9 = i32::from(
                                        *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );
                                    let l13 = i32::from(
                                        *base
                                            .add(7 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>(),
                                    );

                                    super::super::super::super::scheduler::core_libs::types::ExportDef{
              export_type: _rt::string_lift(bytes5),
              name: _rt::string_lift(bytes8),
              scope: match l9 {
                0 => None,
                1 => {
                  let e = {
                    let l10 = *base.add(5*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l11 = *base.add(6*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    let len12 = l11;
                    let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                    _rt::string_lift(bytes12)
                  };
                  Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
              },
              default_value: match l13 {
                0 => None,
                1 => {
                  let e = {
                    let l14 = *base.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l15 = *base.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    let len16 = l15;
                    let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);

                    _rt::string_lift(bytes16)
                  };
                  Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
              },
            }
                                };
                                result17.push(e17);
                            }
                            _rt::cabi_dealloc(
                                base17,
                                len17 * (10 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            T::do_http_action(super::super::super::super::scheduler::core_libs::types::ActionDef{
          id: _rt::string_lift(bytes0),
          call: _rt::string_lift(bytes1),
          with_params: _rt::string_lift(bytes2),
          exports: result17,
        })
                        };
                        let ptr19 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result18 {
                            Ok(e) => {
                                *ptr19.add(0).cast::<u8>() = (0i32) as u8;
                                let super::super::super::super::exports::scheduler::executor_types::types::ActionOutcome{ status:status20, detail:detail20, } = e;
                                *ptr19.add(::core::mem::size_of::<*const u8>()).cast::<u8>() =
                                    (status20.clone() as i32) as u8;
                                match detail20 {
                                    Some(e) => {
                                        *ptr19
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec21 = (e.into_bytes()).into_boxed_slice();
                                        let ptr21 = vec21.as_ptr().cast::<u8>();
                                        let len21 = vec21.len();
                                        ::core::mem::forget(vec21);
                                        *ptr19
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len21;
                                        *ptr19
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr21.cast_mut();
                                    }
                                    None => {
                                        *ptr19
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                    }
                                };
                            }
                            Err(e) => {
                                *ptr19.add(0).cast::<u8>() = (1i32) as u8;
                                let vec22 = (e.into_bytes()).into_boxed_slice();
                                let ptr22 = vec22.as_ptr().cast::<u8>();
                                let len22 = vec22.len();
                                ::core::mem::forget(vec22);
                                *ptr19
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len22;
                                *ptr19
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr22.cast_mut();
                            }
                        };
                        ptr19
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_do_http_action<T: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = i32::from(
                                    *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>(),
                                );
                                match l1 {
                                    0 => (),
                                    _ => {
                                        let l2 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l3 = *arg0
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l2, l3, 1);
                                    }
                                }
                            }
                            _ => {
                                let l4 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l4, l5, 1);
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_release_component_cabi<T: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T::release_component() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result0 {
                            Ok(_) => {
                                *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            }
                            Err(e) => {
                                *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                                let vec2 = (e.into_bytes()).into_boxed_slice();
                                let ptr2 = vec2.as_ptr().cast::<u8>();
                                let len2 = vec2.len();
                                ::core::mem::forget(vec2);
                                *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len2;
                                *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr2.cast_mut();
                            }
                        };
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_release_component<T: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => (),
                            _ => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                        }
                    }
                }
                pub trait Guest {
                    #[allow(async_fn_in_trait)]
                    fn init_component() -> Result<(), _rt::String>;
                    #[allow(async_fn_in_trait)]
                    fn do_http_action(action: ActionDef) -> Result<ActionOutcome, _rt::String>;
                    #[allow(async_fn_in_trait)]
                    fn release_component() -> Result<(), _rt::String>;
                }
                #[doc(hidden)]

                macro_rules! __export_scheduler_actions_http_http_component_0_1_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "scheduler:actions-http/http-component@0.1.0#init-component")]
        unsafe extern "C" fn export_init_component() -> *mut u8 {
          unsafe { $($path_to_types)*::_export_init_component_cabi::<$ty>() }
        }
        #[unsafe(export_name = "cabi_post_scheduler:actions-http/http-component@0.1.0#init-component")]
        unsafe extern "C" fn _post_return_init_component(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_init_component::<$ty>(arg0) }
        }
        #[unsafe(export_name = "scheduler:actions-http/http-component@0.1.0#do-http-action")]
        unsafe extern "C" fn export_do_http_action(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: *mut u8,arg7: usize,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_do_http_action_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) }
        }
        #[unsafe(export_name = "cabi_post_scheduler:actions-http/http-component@0.1.0#do-http-action")]
        unsafe extern "C" fn _post_return_do_http_action(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_do_http_action::<$ty>(arg0) }
        }
        #[unsafe(export_name = "scheduler:actions-http/http-component@0.1.0#release-component")]
        unsafe extern "C" fn export_release_component() -> *mut u8 {
          unsafe { $($path_to_types)*::_export_release_component_cabi::<$ty>() }
        }
        #[unsafe(export_name = "cabi_post_scheduler:actions-http/http-component@0.1.0#release-component")]
        unsafe extern "C" fn _post_return_release_component(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_release_component::<$ty>(arg0) }
        }
      };);
    }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_actions_http_http_component_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
        pub mod executor_types {

            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type ActionDef =
                    super::super::super::super::scheduler::core_libs::types::ActionDef;
                /// Handle referencing host-maintained action context state.
                pub type ActionContext = u64;
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum ActionStatus {
                    Success,
                    Failed,
                }
                impl ::core::fmt::Debug for ActionStatus {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            ActionStatus::Success => {
                                f.debug_tuple("ActionStatus::Success").finish()
                            }
                            ActionStatus::Failed => f.debug_tuple("ActionStatus::Failed").finish(),
                        }
                    }
                }

                impl ActionStatus {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> ActionStatus {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => ActionStatus::Success,
                            1 => ActionStatus::Failed,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Action execution outcome
                #[derive(Clone)]
                pub struct ActionOutcome {
                    pub status: ActionStatus,
                    pub detail: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ActionOutcome {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("ActionOutcome")
                            .field("status", &self.status)
                            .field("detail", &self.detail)
                            .finish()
                    }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum TaskKind {
                    Action,
                    End,
                }
                impl ::core::fmt::Debug for TaskKind {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            TaskKind::Action => f.debug_tuple("TaskKind::Action").finish(),
                            TaskKind::End => f.debug_tuple("TaskKind::End").finish(),
                        }
                    }
                }

                impl TaskKind {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> TaskKind {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => TaskKind::Action,
                            1 => TaskKind::End,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                #[derive(Clone)]
                pub struct WbsEdge {
                    pub target: _rt::String,
                    pub condition: Option<_rt::String>,
                    pub label: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for WbsEdge {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("WbsEdge")
                            .field("target", &self.target)
                            .field("condition", &self.condition)
                            .field("label", &self.label)
                            .finish()
                    }
                }
                /// WBS task for dynamic insertion
                #[derive(Clone)]
                pub struct WbsTask {
                    pub id: _rt::String,
                    pub action_id: Option<_rt::String>,
                    pub kind: TaskKind,
                    pub outgoing: _rt::Vec<WbsEdge>,
                }
                impl ::core::fmt::Debug for WbsTask {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("WbsTask")
                            .field("id", &self.id)
                            .field("action-id", &self.action_id)
                            .field("kind", &self.kind)
                            .field("outgoing", &self.outgoing)
                            .finish()
                    }
                }
                #[doc(hidden)]

                macro_rules! __export_scheduler_executor_types_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _: () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_executor_types_types_0_1_0_cabi;
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }

    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }

    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }

    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }

    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::vec::Vec;

    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }

    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }

    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }

    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }

    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_http_action_component_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::scheduler::executor_types::types::__export_scheduler_executor_types_types_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::scheduler::executor_types::types);
  $($path_to_types_root)*::exports::scheduler::actions_http::http_component::__export_scheduler_actions_http_http_component_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::scheduler::actions_http::http_component);
  )
}
#[doc(inline)]
pub(crate) use __export_http_action_component_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.48.0:scheduler:actions-http@0.1.0:http-action-component:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1697] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x95\x0c\x01A\x02\x01\
A\x0c\x01B\x1a\x01m\x02\x04ipv4\x04ipv6\x04\0\x0eaddress-family\x03\0\0\x01m\x02\
\x03tcp\x03udp\x04\0\x0fsocket-protocol\x03\0\x02\x01r\x02\x04hosts\x04port{\x04\
\0\x0esocket-address\x03\0\x04\x01y\x04\0\x0dsocket-handle\x03\0\x06\x01m\x0a\x12\
connection-refused\x10connection-reset\x12connection-aborted\x13network-unreacha\
ble\x0eaddress-in-use\x15address-not-available\x07timeout\x0bwould-block\x0dinva\
lid-input\x05other\x04\0\x0csocket-error\x03\0\x08\x01j\x01\x07\x01\x09\x01@\x02\
\x06family\x01\x08protocol\x03\0\x0a\x04\0\x0dcreate-socket\x01\x0b\x01j\0\x01\x09\
\x01@\x02\x06socket\x07\x07address\x05\0\x0c\x04\0\x07connect\x01\x0d\x04\0\x04b\
ind\x01\x0d\x01p}\x01j\x01w\x01\x09\x01@\x02\x06socket\x07\x04data\x0e\0\x0f\x04\
\0\x04send\x01\x10\x01j\x01\x0e\x01\x09\x01@\x02\x06socket\x07\x0amax-lengthw\0\x11\
\x04\0\x07receive\x01\x12\x01@\x01\x06socket\x07\0\x0c\x04\0\x05close\x01\x13\x03\
\0\x20scheduler:core-libs/socket@0.1.0\x05\0\x01B\x14\x01r\x03\x02ids\x0dresourc\
e-types\x0apropertiess\x04\0\x0cresource-def\x03\0\0\x01ks\x01r\x04\x0bexport-ty\
pes\x04names\x05scope\x02\x0ddefault-value\x02\x04\0\x0aexport-def\x03\0\x03\x01\
p\x04\x01r\x04\x02ids\x04calls\x0bwith-paramss\x07exports\x05\x04\0\x0aaction-de\
f\x03\0\x06\x01m\x02\x06action\x03end\x04\0\x09node-type\x03\0\x08\x01r\x03\x02t\
os\x09condition\x02\x05label\x02\x04\0\x0dworkflow-edge\x03\0\x0a\x01p\x0b\x01r\x04\
\x02ids\x09node-type\x09\x06action\x02\x05edges\x0c\x04\0\x0dworkflow-node\x03\0\
\x0d\x01p\x01\x01p\x07\x01p\x0e\x01r\x05\x07versions\x04names\x09resources\x0f\x07\
actions\x10\x05nodes\x11\x04\0\x08scenario\x03\0\x12\x03\0\x1fscheduler:core-lib\
s/types@0.1.0\x05\x01\x02\x03\0\x01\x0aaction-def\x02\x03\0\x01\x0aexport-def\x01\
B\x12\x02\x03\x02\x01\x02\x04\0\x0aaction-def\x03\0\0\x02\x03\x02\x01\x03\x04\0\x0a\
export-def\x03\0\x02\x01w\x04\0\x0eaction-context\x03\0\x04\x01m\x02\x07success\x06\
failed\x04\0\x0daction-status\x03\0\x06\x01ks\x01r\x02\x06status\x07\x06detail\x08\
\x04\0\x0eaction-outcome\x03\0\x09\x01m\x02\x06action\x03end\x04\0\x09task-kind\x03\
\0\x0b\x01r\x03\x06targets\x09condition\x08\x05label\x08\x04\0\x08wbs-edge\x03\0\
\x0d\x01p\x0e\x01r\x04\x02ids\x09action-id\x08\x04kind\x0c\x08outgoing\x0f\x04\0\
\x08wbs-task\x03\0\x10\x04\0$scheduler:executor-types/types@0.1.0\x05\x04\x02\x03\
\0\x02\x0aaction-def\x02\x03\0\x02\x0eaction-outcome\x01B\x0b\x02\x03\x02\x01\x05\
\x04\0\x0aaction-def\x03\0\0\x02\x03\x02\x01\x06\x04\0\x0eaction-outcome\x03\0\x02\
\x01j\0\x01s\x01@\0\0\x04\x04\0\x0einit-component\x01\x05\x01j\x01\x03\x01s\x01@\
\x01\x06action\x01\0\x06\x04\0\x0edo-http-action\x01\x07\x04\0\x11release-compon\
ent\x01\x05\x04\0+scheduler:actions-http/http-component@0.1.0\x05\x07\x04\02sche\
duler:actions-http/http-action-component@0.1.0\x04\0\x0b\x1b\x01\0\x15http-actio\
n-component\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.241.2\x10wit-bindgen-rust\x060.48.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
