[package]
name = "packet-engine"
version = "0.1.0"
edition = "2024"
autobins = false

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "ntx:packet"

[package.metadata.component.target]
path = "../wit/packet-engine"
world = "packet-engine"

[dependencies]
wit-bindgen = { version = "0.49.0", features = ["realloc"] }
