[template]
# Use the folder name by default.
name = "{{project-name}}"

# Only include these files when generating.
include = [
  ".cargo/**",
  ".gitignore",
  "Cargo.toml",
  "README.md",
  "build.rs",
  "src/**",
  "wit/deps.toml",
  "wit/deps.lock",
]
