// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod scheduler {
        pub mod executor {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct ExportDef {
                    pub export_type: _rt::String,
                    pub name: _rt::String,
                    pub scope: Option<_rt::String>,
                    pub default_value: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ExportDef {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExportDef")
                            .field("export-type", &self.export_type)
                            .field("name", &self.name)
                            .field("scope", &self.scope)
                            .field("default-value", &self.default_value)
                            .finish()
                    }
                }
                /// Action definition (from core-libs)
                #[derive(Clone)]
                pub struct ActionDef {
                    pub id: _rt::String,
                    pub call: _rt::String,
                    pub with_params: _rt::String,
                    /// JSON string
                    pub exports: _rt::Vec<ExportDef>,
                }
                impl ::core::fmt::Debug for ActionDef {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ActionDef")
                            .field("id", &self.id)
                            .field("call", &self.call)
                            .field("with-params", &self.with_params)
                            .field("exports", &self.exports)
                            .finish()
                    }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum ActionStatus {
                    Success,
                    Failed,
                }
                impl ::core::fmt::Debug for ActionStatus {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ActionStatus::Success => {
                                f.debug_tuple("ActionStatus::Success").finish()
                            }
                            ActionStatus::Failed => {
                                f.debug_tuple("ActionStatus::Failed").finish()
                            }
                        }
                    }
                }
                impl ActionStatus {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> ActionStatus {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => ActionStatus::Success,
                            1 => ActionStatus::Failed,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Action execution outcome
                #[derive(Clone)]
                pub struct ActionOutcome {
                    pub status: ActionStatus,
                    pub detail: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for ActionOutcome {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ActionOutcome")
                            .field("status", &self.status)
                            .field("detail", &self.detail)
                            .finish()
                    }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum TaskKind {
                    Action,
                    End,
                }
                impl ::core::fmt::Debug for TaskKind {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            TaskKind::Action => {
                                f.debug_tuple("TaskKind::Action").finish()
                            }
                            TaskKind::End => f.debug_tuple("TaskKind::End").finish(),
                        }
                    }
                }
                impl TaskKind {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> TaskKind {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => TaskKind::Action,
                            1 => TaskKind::End,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[derive(Clone)]
                pub struct WbsEdge {
                    pub target: _rt::String,
                    pub condition: Option<_rt::String>,
                    pub label: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for WbsEdge {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("WbsEdge")
                            .field("target", &self.target)
                            .field("condition", &self.condition)
                            .field("label", &self.label)
                            .finish()
                    }
                }
                /// WBS task for dynamic insertion
                #[derive(Clone)]
                pub struct WbsTask {
                    pub id: _rt::String,
                    pub action_id: Option<_rt::String>,
                    pub kind: TaskKind,
                    pub outgoing: _rt::Vec<WbsEdge>,
                }
                impl ::core::fmt::Debug for WbsTask {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("WbsTask")
                            .field("id", &self.id)
                            .field("action-id", &self.action_id)
                            .field("kind", &self.kind)
                            .field("outgoing", &self.outgoing)
                            .finish()
                    }
                }
                #[doc(hidden)]
                macro_rules! __export_scheduler_executor_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_executor_types_0_1_0_cabi;
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod context {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ActionDef = super::super::super::super::exports::scheduler::executor::types::ActionDef;
                pub type WbsTask = super::super::super::super::exports::scheduler::executor::types::WbsTask;
                pub type WbsEdge = super::super::super::super::exports::scheduler::executor::types::WbsEdge;
                /// Action execution context (opaque handle for this interface)
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ActionContext {
                    handle: _rt::Resource<ActionContext>,
                }
                type _ActionContextRep<T> = Option<T>;
                impl ActionContext {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `ActionContext`.
                    pub fn new<T: GuestActionContext>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ActionContextRep<T> = Some(val);
                        let ptr: *mut _ActionContextRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestActionContext>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestActionContext>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestActionContext>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _ActionContextRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestActionContext>(
                        &self,
                    ) -> *mut _ActionContextRep<T> {
                        ActionContext::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`ActionContext`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ActionContextBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a ActionContext>,
                }
                impl<'a> ActionContextBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestActionContext>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _ActionContextRep<T> {
                        ActionContext::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for ActionContext {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]scheduler:executor/context@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]action-context"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_action_context_cabi<
                    T: GuestActionContext,
                >() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = ActionContext::new(T::new());
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_action_context_register_action_cabi<
                    T: GuestActionContext,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: *mut u8,
                    arg8: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let len1 = arg4;
                    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
                    let len2 = arg6;
                    let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
                    let base17 = arg7;
                    let len17 = arg8;
                    let mut result17 = _rt::Vec::with_capacity(len17);
                    for i in 0..len17 {
                        let base = base17
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        let e17 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = i32::from(
                                *base
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l13 = i32::from(
                                *base
                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            super::super::super::super::exports::scheduler::executor::types::ExportDef {
                                export_type: _rt::string_lift(bytes5),
                                name: _rt::string_lift(bytes8),
                                scope: match l9 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l10 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l11 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len12 = l11;
                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                l10.cast(),
                                                len12,
                                                len12,
                                            );
                                            _rt::string_lift(bytes12)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                default_value: match l13 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l14 = *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l15 = *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len16 = l15;
                                            let bytes16 = _rt::Vec::from_raw_parts(
                                                l14.cast(),
                                                len16,
                                                len16,
                                            );
                                            _rt::string_lift(bytes16)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result17.push(e17);
                    }
                    _rt::cabi_dealloc(
                        base17,
                        len17 * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    T::register_action(
                        unsafe { ActionContextBorrow::lift(arg0 as u32 as usize) }.get(),
                        super::super::super::super::exports::scheduler::executor::types::ActionDef {
                            id: _rt::string_lift(bytes0),
                            call: _rt::string_lift(bytes1),
                            with_params: _rt::string_lift(bytes2),
                            exports: result17,
                        },
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_action_context_add_task_cabi<
                    T: GuestActionContext,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let base13 = arg7;
                    let len13 = arg8;
                    let mut result13 = _rt::Vec::with_capacity(len13);
                    for i in 0..len13 {
                        let base = base13
                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                        let e13 = {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len4 = l3;
                            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                            let l5 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l9 = i32::from(
                                *base
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            super::super::super::super::exports::scheduler::executor::types::WbsEdge {
                                target: _rt::string_lift(bytes4),
                                condition: match l5 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l6 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l7 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len8 = l7;
                                            let bytes8 = _rt::Vec::from_raw_parts(
                                                l6.cast(),
                                                len8,
                                                len8,
                                            );
                                            _rt::string_lift(bytes8)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                label: match l9 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l10 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l11 = *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len12 = l11;
                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                l10.cast(),
                                                len12,
                                                len12,
                                            );
                                            _rt::string_lift(bytes12)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result13.push(e13);
                    }
                    _rt::cabi_dealloc(
                        base13,
                        len13 * (8 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    T::add_task(
                        unsafe { ActionContextBorrow::lift(arg0 as u32 as usize) }.get(),
                        super::super::super::super::exports::scheduler::executor::types::WbsTask {
                            id: _rt::string_lift(bytes0),
                            action_id: match arg3 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len1 = arg5;
                                        let bytes1 = _rt::Vec::from_raw_parts(
                                            arg4.cast(),
                                            len1,
                                            len1,
                                        );
                                        _rt::string_lift(bytes1)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            kind: super::super::super::super::exports::scheduler::executor::types::TaskKind::_lift(
                                arg6 as u8,
                            ),
                            outgoing: result13,
                        },
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_action_context_remove_task_cabi<
                    T: GuestActionContext,
                >(arg0: *mut u8, arg1: *mut u8, arg2: usize) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    T::remove_task(
                        unsafe { ActionContextBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::string_lift(bytes0),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_action_context_update_task_cabi<
                    T: GuestActionContext,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let base13 = arg7;
                    let len13 = arg8;
                    let mut result13 = _rt::Vec::with_capacity(len13);
                    for i in 0..len13 {
                        let base = base13
                            .add(i * (8 * ::core::mem::size_of::<*const u8>()));
                        let e13 = {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len4 = l3;
                            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                            let l5 = i32::from(
                                *base
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l9 = i32::from(
                                *base
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            super::super::super::super::exports::scheduler::executor::types::WbsEdge {
                                target: _rt::string_lift(bytes4),
                                condition: match l5 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l6 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l7 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len8 = l7;
                                            let bytes8 = _rt::Vec::from_raw_parts(
                                                l6.cast(),
                                                len8,
                                                len8,
                                            );
                                            _rt::string_lift(bytes8)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                label: match l9 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l10 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l11 = *base
                                                .add(7 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len12 = l11;
                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                l10.cast(),
                                                len12,
                                                len12,
                                            );
                                            _rt::string_lift(bytes12)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result13.push(e13);
                    }
                    _rt::cabi_dealloc(
                        base13,
                        len13 * (8 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    T::update_task(
                        unsafe { ActionContextBorrow::lift(arg0 as u32 as usize) }.get(),
                        super::super::super::super::exports::scheduler::executor::types::WbsTask {
                            id: _rt::string_lift(bytes0),
                            action_id: match arg3 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len1 = arg5;
                                        let bytes1 = _rt::Vec::from_raw_parts(
                                            arg4.cast(),
                                            len1,
                                            len1,
                                        );
                                        _rt::string_lift(bytes1)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            kind: super::super::super::super::exports::scheduler::executor::types::TaskKind::_lift(
                                arg6 as u8,
                            ),
                            outgoing: result13,
                        },
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_action_context_add_edge_cabi<
                    T: GuestActionContext,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: i32,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: i32,
                    arg9: *mut u8,
                    arg10: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let len1 = arg4;
                    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
                    T::add_edge(
                        unsafe { ActionContextBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::string_lift(bytes0),
                        super::super::super::super::exports::scheduler::executor::types::WbsEdge {
                            target: _rt::string_lift(bytes1),
                            condition: match arg5 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len2 = arg7;
                                        let bytes2 = _rt::Vec::from_raw_parts(
                                            arg6.cast(),
                                            len2,
                                            len2,
                                        );
                                        _rt::string_lift(bytes2)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            label: match arg8 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len3 = arg10;
                                        let bytes3 = _rt::Vec::from_raw_parts(
                                            arg9.cast(),
                                            len3,
                                            len3,
                                        );
                                        _rt::string_lift(bytes3)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_action_context_remove_edge_cabi<
                    T: GuestActionContext,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let len1 = arg4;
                    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
                    T::remove_edge(
                        unsafe { ActionContextBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                }
                pub trait Guest {
                    type ActionContext: GuestActionContext;
                }
                pub trait GuestActionContext: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]scheduler:executor/context@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]action-context"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]scheduler:executor/context@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]action-context"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new() -> Self;
                    /// Queue an event to register a new action
                    fn register_action(&self, action: ActionDef) -> ();
                    /// Queue an event to add a task
                    fn add_task(&self, task: WbsTask) -> ();
                    /// Queue an event to remove a task
                    fn remove_task(&self, task_id: _rt::String) -> ();
                    /// Queue an event to update a task
                    fn update_task(&self, task: WbsTask) -> ();
                    /// Queue an event to add an edge
                    fn add_edge(&self, from_id: _rt::String, edge: WbsEdge) -> ();
                    /// Queue an event to remove an edge
                    fn remove_edge(
                        &self,
                        from_id: _rt::String,
                        target: _rt::String,
                    ) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_scheduler_executor_context_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "scheduler:executor/context@0.1.0#[constructor]action-context")]
                        unsafe extern "C" fn export_constructor_action_context() -> i32 {
                        unsafe { $($path_to_types)*::
                        _export_constructor_action_context_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ActionContext > () } } #[unsafe
                        (export_name =
                        "scheduler:executor/context@0.1.0#[method]action-context.register-action")]
                        unsafe extern "C" fn
                        export_method_action_context_register_action(arg0 : * mut u8,
                        arg1 : * mut u8, arg2 : usize, arg3 : * mut u8, arg4 : usize,
                        arg5 : * mut u8, arg6 : usize, arg7 : * mut u8, arg8 : usize,) {
                        unsafe { $($path_to_types)*::
                        _export_method_action_context_register_action_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ActionContext > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "scheduler:executor/context@0.1.0#[method]action-context.add-task")]
                        unsafe extern "C" fn export_method_action_context_add_task(arg0 :
                        * mut u8, arg1 : * mut u8, arg2 : usize, arg3 : i32, arg4 : * mut
                        u8, arg5 : usize, arg6 : i32, arg7 : * mut u8, arg8 : usize,) {
                        unsafe { $($path_to_types)*::
                        _export_method_action_context_add_task_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ActionContext > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "scheduler:executor/context@0.1.0#[method]action-context.remove-task")]
                        unsafe extern "C" fn
                        export_method_action_context_remove_task(arg0 : * mut u8, arg1 :
                        * mut u8, arg2 : usize,) { unsafe { $($path_to_types)*::
                        _export_method_action_context_remove_task_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ActionContext > (arg0, arg1, arg2)
                        } } #[unsafe (export_name =
                        "scheduler:executor/context@0.1.0#[method]action-context.update-task")]
                        unsafe extern "C" fn
                        export_method_action_context_update_task(arg0 : * mut u8, arg1 :
                        * mut u8, arg2 : usize, arg3 : i32, arg4 : * mut u8, arg5 :
                        usize, arg6 : i32, arg7 : * mut u8, arg8 : usize,) { unsafe {
                        $($path_to_types)*::
                        _export_method_action_context_update_task_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ActionContext > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "scheduler:executor/context@0.1.0#[method]action-context.add-edge")]
                        unsafe extern "C" fn export_method_action_context_add_edge(arg0 :
                        * mut u8, arg1 : * mut u8, arg2 : usize, arg3 : * mut u8, arg4 :
                        usize, arg5 : i32, arg6 : * mut u8, arg7 : usize, arg8 : i32,
                        arg9 : * mut u8, arg10 : usize,) { unsafe { $($path_to_types)*::
                        _export_method_action_context_add_edge_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ActionContext > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) } } #[unsafe
                        (export_name =
                        "scheduler:executor/context@0.1.0#[method]action-context.remove-edge")]
                        unsafe extern "C" fn
                        export_method_action_context_remove_edge(arg0 : * mut u8, arg1 :
                        * mut u8, arg2 : usize, arg3 : * mut u8, arg4 : usize,) { unsafe
                        { $($path_to_types)*::
                        _export_method_action_context_remove_edge_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ActionContext > (arg0, arg1, arg2,
                        arg3, arg4) } } const _ : () = { #[doc(hidden)] #[unsafe
                        (export_name =
                        "scheduler:executor/context@0.1.0#[dtor]action-context")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: ActionContext::dtor::< <$ty
                        as $($path_to_types)*:: Guest >::ActionContext > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_executor_context_0_1_0_cabi;
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod component_api {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ActionDef = super::super::super::super::exports::scheduler::executor::types::ActionDef;
                pub type ActionOutcome = super::super::super::super::exports::scheduler::executor::types::ActionOutcome;
                pub type ActionContext = super::super::super::super::exports::scheduler::executor::context::ActionContext;
                pub type ActionContextBorrow<'a> = super::super::super::super::exports::scheduler::executor::context::ActionContextBorrow<
                    'a,
                >;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_execute_action_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                    arg8: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                    let base17 = arg6;
                    let len17 = arg7;
                    let mut result17 = _rt::Vec::with_capacity(len17);
                    for i in 0..len17 {
                        let base = base17
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        let e17 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = i32::from(
                                *base
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l13 = i32::from(
                                *base
                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            super::super::super::super::exports::scheduler::executor::types::ExportDef {
                                export_type: _rt::string_lift(bytes5),
                                name: _rt::string_lift(bytes8),
                                scope: match l9 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l10 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l11 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len12 = l11;
                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                l10.cast(),
                                                len12,
                                                len12,
                                            );
                                            _rt::string_lift(bytes12)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                default_value: match l13 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l14 = *base
                                                .add(8 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l15 = *base
                                                .add(9 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len16 = l15;
                                            let bytes16 = _rt::Vec::from_raw_parts(
                                                l14.cast(),
                                                len16,
                                                len16,
                                            );
                                            _rt::string_lift(bytes16)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result17.push(e17);
                    }
                    _rt::cabi_dealloc(
                        base17,
                        len17 * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result18 = T::execute_action(
                        super::super::super::super::exports::scheduler::executor::types::ActionDef {
                            id: _rt::string_lift(bytes0),
                            call: _rt::string_lift(bytes1),
                            with_params: _rt::string_lift(bytes2),
                            exports: result17,
                        },
                        unsafe {
                            super::super::super::super::exports::scheduler::executor::context::ActionContext::from_handle(
                                arg8 as u32,
                            )
                        },
                    );
                    let ptr19 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result18 {
                        Ok(e) => {
                            *ptr19.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::exports::scheduler::executor::types::ActionOutcome {
                                status: status20,
                                detail: detail20,
                            } = e;
                            *ptr19
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (status20.clone() as i32) as u8;
                            match detail20 {
                                Some(e) => {
                                    *ptr19
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec21 = (e.into_bytes()).into_boxed_slice();
                                    let ptr21 = vec21.as_ptr().cast::<u8>();
                                    let len21 = vec21.len();
                                    ::core::mem::forget(vec21);
                                    *ptr19
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len21;
                                    *ptr19
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr21.cast_mut();
                                }
                                None => {
                                    *ptr19
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        Err(e) => {
                            *ptr19.add(0).cast::<u8>() = (1i32) as u8;
                            let vec22 = (e.into_bytes()).into_boxed_slice();
                            let ptr22 = vec22.as_ptr().cast::<u8>();
                            let len22 = vec22.len();
                            ::core::mem::forget(vec22);
                            *ptr19
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len22;
                            *ptr19
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr22.cast_mut();
                        }
                    };
                    ptr19
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_execute_action<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn execute_action(
                        action: ActionDef,
                        ctx: ActionContext,
                    ) -> Result<ActionOutcome, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_scheduler_executor_component_api_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "scheduler:executor/component-api@0.1.0#execute-action")] unsafe
                        extern "C" fn export_execute_action(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8, arg5 :
                        usize, arg6 : * mut u8, arg7 : usize, arg8 : i32,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_execute_action_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) } }
                        #[unsafe (export_name =
                        "cabi_post_scheduler:executor/component-api@0.1.0#execute-action")]
                        unsafe extern "C" fn _post_return_execute_action(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_execute_action::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_scheduler_executor_component_api_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_scheduler_executor_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::scheduler::executor::types::__export_scheduler_executor_types_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::scheduler::executor::types);
        $($path_to_types_root)*::
        exports::scheduler::executor::context::__export_scheduler_executor_context_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::scheduler::executor::context);
        $($path_to_types_root)*::
        exports::scheduler::executor::component_api::__export_scheduler_executor_component_api_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::scheduler::executor::component_api);
    };
}
#[doc(inline)]
pub(crate) use __export_scheduler_executor_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:scheduler:executor@0.1.0:scheduler-executor:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1290] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x81\x09\x01A\x02\x01\
A\x0b\x01B\x11\x01ks\x01r\x04\x0bexport-types\x04names\x05scope\0\x0ddefault-val\
ue\0\x04\0\x0aexport-def\x03\0\x01\x01p\x02\x01r\x04\x02ids\x04calls\x0bwith-par\
amss\x07exports\x03\x04\0\x0aaction-def\x03\0\x04\x01m\x02\x07success\x06failed\x04\
\0\x0daction-status\x03\0\x06\x01r\x02\x06status\x07\x06detail\0\x04\0\x0eaction\
-outcome\x03\0\x08\x01m\x02\x06action\x03end\x04\0\x09task-kind\x03\0\x0a\x01r\x03\
\x06targets\x09condition\0\x05label\0\x04\0\x08wbs-edge\x03\0\x0c\x01p\x0d\x01r\x04\
\x02ids\x09action-id\0\x04kind\x0b\x08outgoing\x0e\x04\0\x08wbs-task\x03\0\x0f\x04\
\0\x1escheduler:executor/types@0.1.0\x05\0\x02\x03\0\0\x0aaction-def\x02\x03\0\0\
\x08wbs-task\x02\x03\0\0\x08wbs-edge\x01B\x16\x02\x03\x02\x01\x01\x04\0\x0aactio\
n-def\x03\0\0\x02\x03\x02\x01\x02\x04\0\x08wbs-task\x03\0\x02\x02\x03\x02\x01\x03\
\x04\0\x08wbs-edge\x03\0\x04\x04\0\x0eaction-context\x03\x01\x01i\x06\x01@\0\0\x07\
\x04\0\x1b[constructor]action-context\x01\x08\x01h\x06\x01@\x02\x04self\x09\x06a\
ction\x01\x01\0\x04\0&[method]action-context.register-action\x01\x0a\x01@\x02\x04\
self\x09\x04task\x03\x01\0\x04\0\x1f[method]action-context.add-task\x01\x0b\x01@\
\x02\x04self\x09\x07task-ids\x01\0\x04\0\"[method]action-context.remove-task\x01\
\x0c\x04\0\"[method]action-context.update-task\x01\x0b\x01@\x03\x04self\x09\x07f\
rom-ids\x04edge\x05\x01\0\x04\0\x1f[method]action-context.add-edge\x01\x0d\x01@\x03\
\x04self\x09\x07from-ids\x06targets\x01\0\x04\0\"[method]action-context.remove-e\
dge\x01\x0e\x04\0\x20scheduler:executor/context@0.1.0\x05\x04\x02\x03\0\0\x0eact\
ion-outcome\x02\x03\0\x01\x0eaction-context\x01B\x0a\x02\x03\x02\x01\x01\x04\0\x0a\
action-def\x03\0\0\x02\x03\x02\x01\x05\x04\0\x0eaction-outcome\x03\0\x02\x02\x03\
\x02\x01\x06\x04\0\x0eaction-context\x03\0\x04\x01i\x05\x01j\x01\x03\x01s\x01@\x02\
\x06action\x01\x03ctx\x06\0\x07\x04\0\x0eexecute-action\x01\x08\x04\0&scheduler:\
executor/component-api@0.1.0\x05\x07\x04\0+scheduler:executor/scheduler-executor\
@0.1.0\x04\0\x0b\x18\x01\0\x12scheduler-executor\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
