package ntx:host@0.1.0;
use ntx:net-types/types@0.1.0;


world hostnet {
    // The guest imports these host-provided interfaces.
    import types;
    import resources;
    import udp-socket-control;
    // End-state RX pulling interface used by the composed scheduler.
    import rx-ring;
    export types;
    export resources;
    export udp-socket-control;
}

